// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: passage_register.proto

package com.axismobfintech.gpb.transactions;

public final class PassageRegister {
  private PassageRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RegisterPassageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.RegisterPassage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The operatorId.
     */
    java.lang.String getOperatorId();
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The bytes for operatorId.
     */
    com.google.protobuf.ByteString
        getOperatorIdBytes();

    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The readerSerialNumber.
     */
    java.lang.String getReaderSerialNumber();
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The bytes for readerSerialNumber.
     */
    com.google.protobuf.ByteString
        getReaderSerialNumberBytes();

    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The deviceSerialNumber.
     */
    java.lang.String getDeviceSerialNumber();
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The bytes for deviceSerialNumber.
     */
    com.google.protobuf.ByteString
        getDeviceSerialNumberBytes();

    /**
     * <pre>
     *Código de autorização de registro
     * </pre>
     *
     * <code>int32 register_code = 5;</code>
     * @return The registerCode.
     */
    int getRegisterCode();

    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     * @return Whether the passageDate field is set.
     */
    boolean hasPassageDate();
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     * @return The passageDate.
     */
    com.google.protobuf.Timestamp getPassageDate();

    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     * @return Whether the transactionDate field is set.
     */
    boolean hasTransactionDate();
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     * @return The transactionDate.
     */
    com.google.protobuf.Timestamp getTransactionDate();

    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @return The deviceSuid.
     */
    java.lang.String getDeviceSuid();
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @return The bytes for deviceSuid.
     */
    com.google.protobuf.ByteString
        getDeviceSuidBytes();

    /**
     * <pre>
     *Hash da PAN do cartão utilizado
     * </pre>
     *
     * <code>bytes pan_hash = 9;</code>
     * @return The panHash.
     */
    com.google.protobuf.ByteString getPanHash();

    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @return The parCard.
     */
    java.lang.String getParCard();
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @return The bytes for parCard.
     */
    com.google.protobuf.ByteString
        getParCardBytes();

    /**
     * <pre>
     *Dados de processamento da transação sem contato obtidos do leitor sem contato.
     * </pre>
     *
     * <code>bytes transaction_data = 11;</code>
     * @return The transactionData.
     */
    com.google.protobuf.ByteString getTransactionData();

    /**
     * <pre>
     *Request: Versão dos parâmetros EMV para configuração do leitor.
     * </pre>
     *
     * <code>int32 emv_parameters_version = 12;</code>
     * @return The emvParametersVersion.
     */
    int getEmvParametersVersion();

    /**
     * <pre>
     *Request: Versão das tabelas de BIN disponíveis no validador.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 13;</code>
     * @return The binParametersVersion.
     */
    int getBinParametersVersion();

    /**
     * <pre>
     *Request: Versão da lista de exceção disponível no validador.
     * </pre>
     *
     * <code>int32 restriction_list_version = 14;</code>
     * @return The restrictionListVersion.
     */
    int getRestrictionListVersion();

    /**
     * <pre>
     *Valor da transação (presente se disponível)
     * </pre>
     *
     * <code>int32 transaction_value = 15;</code>
     * @return The transactionValue.
     */
    int getTransactionValue();

    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @return The lineId.
     */
    java.lang.String getLineId();
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @return The bytes for lineId.
     */
    com.google.protobuf.ByteString
        getLineIdBytes();

    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @return The vehicleId.
     */
    java.lang.String getVehicleId();
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @return The bytes for vehicleId.
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @return The geolocation.
     */
    java.lang.String getGeolocation();
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @return The bytes for geolocation.
     */
    com.google.protobuf.ByteString
        getGeolocationBytes();
  }
  /**
   * Protobuf type {@code axis.transactions.RegisterPassage}
   */
  public  static final class RegisterPassage extends
      com.google.protobuf.GeneratedMessageLite<
          RegisterPassage, RegisterPassage.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.RegisterPassage)
      RegisterPassageOrBuilder {
    private RegisterPassage() {
      deviceId_ = "";
      operatorId_ = "";
      readerSerialNumber_ = "";
      deviceSerialNumber_ = "";
      deviceSuid_ = "";
      panHash_ = com.google.protobuf.ByteString.EMPTY;
      parCard_ = "";
      transactionData_ = com.google.protobuf.ByteString.EMPTY;
      lineId_ = "";
      vehicleId_ = "";
      geolocation_ = "";
    }
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.String deviceId_;
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return deviceId_;
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @param value The deviceId to set.
     */
    private void setDeviceId(
        java.lang.String value) {
      value.getClass();
  
      deviceId_ = value;
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    private void clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @param value The bytes for deviceId to set.
     */
    private void setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceId_ = value.toStringUtf8();
      
    }

    public static final int OPERATOR_ID_FIELD_NUMBER = 2;
    private java.lang.String operatorId_;
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The operatorId.
     */
    @java.lang.Override
    public java.lang.String getOperatorId() {
      return operatorId_;
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The bytes for operatorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperatorIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(operatorId_);
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @param value The operatorId to set.
     */
    private void setOperatorId(
        java.lang.String value) {
      value.getClass();
  
      operatorId_ = value;
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     */
    private void clearOperatorId() {
      
      operatorId_ = getDefaultInstance().getOperatorId();
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @param value The bytes for operatorId to set.
     */
    private void setOperatorIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      operatorId_ = value.toStringUtf8();
      
    }

    public static final int READER_SERIAL_NUMBER_FIELD_NUMBER = 3;
    private java.lang.String readerSerialNumber_;
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The readerSerialNumber.
     */
    @java.lang.Override
    public java.lang.String getReaderSerialNumber() {
      return readerSerialNumber_;
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The bytes for readerSerialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReaderSerialNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(readerSerialNumber_);
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @param value The readerSerialNumber to set.
     */
    private void setReaderSerialNumber(
        java.lang.String value) {
      value.getClass();
  
      readerSerialNumber_ = value;
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     */
    private void clearReaderSerialNumber() {
      
      readerSerialNumber_ = getDefaultInstance().getReaderSerialNumber();
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @param value The bytes for readerSerialNumber to set.
     */
    private void setReaderSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      readerSerialNumber_ = value.toStringUtf8();
      
    }

    public static final int DEVICE_SERIAL_NUMBER_FIELD_NUMBER = 4;
    private java.lang.String deviceSerialNumber_;
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The deviceSerialNumber.
     */
    @java.lang.Override
    public java.lang.String getDeviceSerialNumber() {
      return deviceSerialNumber_;
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The bytes for deviceSerialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceSerialNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceSerialNumber_);
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @param value The deviceSerialNumber to set.
     */
    private void setDeviceSerialNumber(
        java.lang.String value) {
      value.getClass();
  
      deviceSerialNumber_ = value;
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     */
    private void clearDeviceSerialNumber() {
      
      deviceSerialNumber_ = getDefaultInstance().getDeviceSerialNumber();
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @param value The bytes for deviceSerialNumber to set.
     */
    private void setDeviceSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceSerialNumber_ = value.toStringUtf8();
      
    }

    public static final int REGISTER_CODE_FIELD_NUMBER = 5;
    private int registerCode_;
    /**
     * <pre>
     *Código de autorização de registro
     * </pre>
     *
     * <code>int32 register_code = 5;</code>
     * @return The registerCode.
     */
    @java.lang.Override
    public int getRegisterCode() {
      return registerCode_;
    }
    /**
     * <pre>
     *Código de autorização de registro
     * </pre>
     *
     * <code>int32 register_code = 5;</code>
     * @param value The registerCode to set.
     */
    private void setRegisterCode(int value) {
      
      registerCode_ = value;
    }
    /**
     * <pre>
     *Código de autorização de registro
     * </pre>
     *
     * <code>int32 register_code = 5;</code>
     */
    private void clearRegisterCode() {
      
      registerCode_ = 0;
    }

    public static final int PASSAGE_DATE_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp passageDate_;
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     */
    @java.lang.Override
    public boolean hasPassageDate() {
      return passageDate_ != null;
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPassageDate() {
      return passageDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : passageDate_;
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     */
    private void setPassageDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  passageDate_ = value;
      
      }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergePassageDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (passageDate_ != null &&
          passageDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        passageDate_ =
          com.google.protobuf.Timestamp.newBuilder(passageDate_).mergeFrom(value).buildPartial();
      } else {
        passageDate_ = value;
      }
      
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp passage_date = 6;</code>
     */
    private void clearPassageDate() {  passageDate_ = null;
      
    }

    public static final int TRANSACTION_DATE_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp transactionDate_;
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     */
    @java.lang.Override
    public boolean hasTransactionDate() {
      return transactionDate_ != null;
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTransactionDate() {
      return transactionDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : transactionDate_;
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     */
    private void setTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  transactionDate_ = value;
      
      }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (transactionDate_ != null &&
          transactionDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        transactionDate_ =
          com.google.protobuf.Timestamp.newBuilder(transactionDate_).mergeFrom(value).buildPartial();
      } else {
        transactionDate_ = value;
      }
      
    }
    /**
     * <pre>
     *Data e hora da passagem
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
     */
    private void clearTransactionDate() {  transactionDate_ = null;
      
    }

    public static final int DEVICE_SUID_FIELD_NUMBER = 8;
    private java.lang.String deviceSuid_;
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @return The deviceSuid.
     */
    @java.lang.Override
    public java.lang.String getDeviceSuid() {
      return deviceSuid_;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @return The bytes for deviceSuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceSuidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceSuid_);
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @param value The deviceSuid to set.
     */
    private void setDeviceSuid(
        java.lang.String value) {
      value.getClass();
  
      deviceSuid_ = value;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     */
    private void clearDeviceSuid() {
      
      deviceSuid_ = getDefaultInstance().getDeviceSuid();
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 8;</code>
     * @param value The bytes for deviceSuid to set.
     */
    private void setDeviceSuidBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceSuid_ = value.toStringUtf8();
      
    }

    public static final int PAN_HASH_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString panHash_;
    /**
     * <pre>
     *Hash da PAN do cartão utilizado
     * </pre>
     *
     * <code>bytes pan_hash = 9;</code>
     * @return The panHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPanHash() {
      return panHash_;
    }
    /**
     * <pre>
     *Hash da PAN do cartão utilizado
     * </pre>
     *
     * <code>bytes pan_hash = 9;</code>
     * @param value The panHash to set.
     */
    private void setPanHash(com.google.protobuf.ByteString value) {
      value.getClass();
  
      panHash_ = value;
    }
    /**
     * <pre>
     *Hash da PAN do cartão utilizado
     * </pre>
     *
     * <code>bytes pan_hash = 9;</code>
     */
    private void clearPanHash() {
      
      panHash_ = getDefaultInstance().getPanHash();
    }

    public static final int PAR_CARD_FIELD_NUMBER = 10;
    private java.lang.String parCard_;
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @return The parCard.
     */
    @java.lang.Override
    public java.lang.String getParCard() {
      return parCard_;
    }
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @return The bytes for parCard.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParCardBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(parCard_);
    }
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @param value The parCard to set.
     */
    private void setParCard(
        java.lang.String value) {
      value.getClass();
  
      parCard_ = value;
    }
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     */
    private void clearParCard() {
      
      parCard_ = getDefaultInstance().getParCard();
    }
    /**
     * <pre>
     *PAR do cartão utilizado (presente se informado pelo leitor)
     * </pre>
     *
     * <code>string par_card = 10;</code>
     * @param value The bytes for parCard to set.
     */
    private void setParCardBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      parCard_ = value.toStringUtf8();
      
    }

    public static final int TRANSACTION_DATA_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString transactionData_;
    /**
     * <pre>
     *Dados de processamento da transação sem contato obtidos do leitor sem contato.
     * </pre>
     *
     * <code>bytes transaction_data = 11;</code>
     * @return The transactionData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTransactionData() {
      return transactionData_;
    }
    /**
     * <pre>
     *Dados de processamento da transação sem contato obtidos do leitor sem contato.
     * </pre>
     *
     * <code>bytes transaction_data = 11;</code>
     * @param value The transactionData to set.
     */
    private void setTransactionData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      transactionData_ = value;
    }
    /**
     * <pre>
     *Dados de processamento da transação sem contato obtidos do leitor sem contato.
     * </pre>
     *
     * <code>bytes transaction_data = 11;</code>
     */
    private void clearTransactionData() {
      
      transactionData_ = getDefaultInstance().getTransactionData();
    }

    public static final int EMV_PARAMETERS_VERSION_FIELD_NUMBER = 12;
    private int emvParametersVersion_;
    /**
     * <pre>
     *Request: Versão dos parâmetros EMV para configuração do leitor.
     * </pre>
     *
     * <code>int32 emv_parameters_version = 12;</code>
     * @return The emvParametersVersion.
     */
    @java.lang.Override
    public int getEmvParametersVersion() {
      return emvParametersVersion_;
    }
    /**
     * <pre>
     *Request: Versão dos parâmetros EMV para configuração do leitor.
     * </pre>
     *
     * <code>int32 emv_parameters_version = 12;</code>
     * @param value The emvParametersVersion to set.
     */
    private void setEmvParametersVersion(int value) {
      
      emvParametersVersion_ = value;
    }
    /**
     * <pre>
     *Request: Versão dos parâmetros EMV para configuração do leitor.
     * </pre>
     *
     * <code>int32 emv_parameters_version = 12;</code>
     */
    private void clearEmvParametersVersion() {
      
      emvParametersVersion_ = 0;
    }

    public static final int BIN_PARAMETERS_VERSION_FIELD_NUMBER = 13;
    private int binParametersVersion_;
    /**
     * <pre>
     *Request: Versão das tabelas de BIN disponíveis no validador.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 13;</code>
     * @return The binParametersVersion.
     */
    @java.lang.Override
    public int getBinParametersVersion() {
      return binParametersVersion_;
    }
    /**
     * <pre>
     *Request: Versão das tabelas de BIN disponíveis no validador.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 13;</code>
     * @param value The binParametersVersion to set.
     */
    private void setBinParametersVersion(int value) {
      
      binParametersVersion_ = value;
    }
    /**
     * <pre>
     *Request: Versão das tabelas de BIN disponíveis no validador.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 13;</code>
     */
    private void clearBinParametersVersion() {
      
      binParametersVersion_ = 0;
    }

    public static final int RESTRICTION_LIST_VERSION_FIELD_NUMBER = 14;
    private int restrictionListVersion_;
    /**
     * <pre>
     *Request: Versão da lista de exceção disponível no validador.
     * </pre>
     *
     * <code>int32 restriction_list_version = 14;</code>
     * @return The restrictionListVersion.
     */
    @java.lang.Override
    public int getRestrictionListVersion() {
      return restrictionListVersion_;
    }
    /**
     * <pre>
     *Request: Versão da lista de exceção disponível no validador.
     * </pre>
     *
     * <code>int32 restriction_list_version = 14;</code>
     * @param value The restrictionListVersion to set.
     */
    private void setRestrictionListVersion(int value) {
      
      restrictionListVersion_ = value;
    }
    /**
     * <pre>
     *Request: Versão da lista de exceção disponível no validador.
     * </pre>
     *
     * <code>int32 restriction_list_version = 14;</code>
     */
    private void clearRestrictionListVersion() {
      
      restrictionListVersion_ = 0;
    }

    public static final int TRANSACTION_VALUE_FIELD_NUMBER = 15;
    private int transactionValue_;
    /**
     * <pre>
     *Valor da transação (presente se disponível)
     * </pre>
     *
     * <code>int32 transaction_value = 15;</code>
     * @return The transactionValue.
     */
    @java.lang.Override
    public int getTransactionValue() {
      return transactionValue_;
    }
    /**
     * <pre>
     *Valor da transação (presente se disponível)
     * </pre>
     *
     * <code>int32 transaction_value = 15;</code>
     * @param value The transactionValue to set.
     */
    private void setTransactionValue(int value) {
      
      transactionValue_ = value;
    }
    /**
     * <pre>
     *Valor da transação (presente se disponível)
     * </pre>
     *
     * <code>int32 transaction_value = 15;</code>
     */
    private void clearTransactionValue() {
      
      transactionValue_ = 0;
    }

    public static final int LINE_ID_FIELD_NUMBER = 16;
    private java.lang.String lineId_;
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @return The lineId.
     */
    @java.lang.Override
    public java.lang.String getLineId() {
      return lineId_;
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @return The bytes for lineId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLineIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lineId_);
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @param value The lineId to set.
     */
    private void setLineId(
        java.lang.String value) {
      value.getClass();
  
      lineId_ = value;
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     */
    private void clearLineId() {
      
      lineId_ = getDefaultInstance().getLineId();
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 16;</code>
     * @param value The bytes for lineId to set.
     */
    private void setLineIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lineId_ = value.toStringUtf8();
      
    }

    public static final int VEHICLE_ID_FIELD_NUMBER = 17;
    private java.lang.String vehicleId_;
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @return The vehicleId.
     */
    @java.lang.Override
    public java.lang.String getVehicleId() {
      return vehicleId_;
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @return The bytes for vehicleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(vehicleId_);
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @param value The vehicleId to set.
     */
    private void setVehicleId(
        java.lang.String value) {
      value.getClass();
  
      vehicleId_ = value;
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     */
    private void clearVehicleId() {
      
      vehicleId_ = getDefaultInstance().getVehicleId();
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 17;</code>
     * @param value The bytes for vehicleId to set.
     */
    private void setVehicleIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      vehicleId_ = value.toStringUtf8();
      
    }

    public static final int GEOLOCATION_FIELD_NUMBER = 18;
    private java.lang.String geolocation_;
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @return The geolocation.
     */
    @java.lang.Override
    public java.lang.String getGeolocation() {
      return geolocation_;
    }
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @return The bytes for geolocation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGeolocationBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(geolocation_);
    }
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @param value The geolocation to set.
     */
    private void setGeolocation(
        java.lang.String value) {
      value.getClass();
  
      geolocation_ = value;
    }
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     */
    private void clearGeolocation() {
      
      geolocation_ = getDefaultInstance().getGeolocation();
    }
    /**
     * <pre>
     *Geolocalização do validador no momento da geração da passagem
     * </pre>
     *
     * <code>string geolocation = 18;</code>
     * @param value The bytes for geolocation to set.
     */
    private void setGeolocationBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      geolocation_ = value.toStringUtf8();
      
    }

    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.RegisterPassage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.RegisterPassage)
        com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return The deviceId.
       */
      @java.lang.Override
      public java.lang.String getDeviceId() {
        return instance.getDeviceId();
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return The bytes for deviceId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        return instance.getDeviceIdBytes();
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        copyOnWrite();
        instance.clearDeviceId();
        return this;
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return The operatorId.
       */
      @java.lang.Override
      public java.lang.String getOperatorId() {
        return instance.getOperatorId();
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return The bytes for operatorId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOperatorIdBytes() {
        return instance.getOperatorIdBytes();
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @param value The operatorId to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOperatorId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperatorId() {
        copyOnWrite();
        instance.clearOperatorId();
        return this;
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @param value The bytes for operatorId to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOperatorIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return The readerSerialNumber.
       */
      @java.lang.Override
      public java.lang.String getReaderSerialNumber() {
        return instance.getReaderSerialNumber();
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return The bytes for readerSerialNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReaderSerialNumberBytes() {
        return instance.getReaderSerialNumberBytes();
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @param value The readerSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReaderSerialNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setReaderSerialNumber(value);
        return this;
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReaderSerialNumber() {
        copyOnWrite();
        instance.clearReaderSerialNumber();
        return this;
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @param value The bytes for readerSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReaderSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReaderSerialNumberBytes(value);
        return this;
      }

      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return The deviceSerialNumber.
       */
      @java.lang.Override
      public java.lang.String getDeviceSerialNumber() {
        return instance.getDeviceSerialNumber();
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return The bytes for deviceSerialNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceSerialNumberBytes() {
        return instance.getDeviceSerialNumberBytes();
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @param value The deviceSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSerialNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceSerialNumber(value);
        return this;
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceSerialNumber() {
        copyOnWrite();
        instance.clearDeviceSerialNumber();
        return this;
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @param value The bytes for deviceSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceSerialNumberBytes(value);
        return this;
      }

      /**
       * <pre>
       *Código de autorização de registro
       * </pre>
       *
       * <code>int32 register_code = 5;</code>
       * @return The registerCode.
       */
      @java.lang.Override
      public int getRegisterCode() {
        return instance.getRegisterCode();
      }
      /**
       * <pre>
       *Código de autorização de registro
       * </pre>
       *
       * <code>int32 register_code = 5;</code>
       * @param value The registerCode to set.
       * @return This builder for chaining.
       */
      public Builder setRegisterCode(int value) {
        copyOnWrite();
        instance.setRegisterCode(value);
        return this;
      }
      /**
       * <pre>
       *Código de autorização de registro
       * </pre>
       *
       * <code>int32 register_code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegisterCode() {
        copyOnWrite();
        instance.clearRegisterCode();
        return this;
      }

      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      @java.lang.Override
      public boolean hasPassageDate() {
        return instance.hasPassageDate();
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getPassageDate() {
        return instance.getPassageDate();
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      public Builder setPassageDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setPassageDate(value);
        return this;
        }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      public Builder setPassageDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setPassageDate(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      public Builder mergePassageDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergePassageDate(value);
        return this;
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp passage_date = 6;</code>
       */
      public Builder clearPassageDate() {  copyOnWrite();
        instance.clearPassageDate();
        return this;
      }

      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      @java.lang.Override
      public boolean hasTransactionDate() {
        return instance.hasTransactionDate();
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getTransactionDate() {
        return instance.getTransactionDate();
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      public Builder setTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setTransactionDate(value);
        return this;
        }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      public Builder setTransactionDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setTransactionDate(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      public Builder mergeTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeTransactionDate(value);
        return this;
      }
      /**
       * <pre>
       *Data e hora da passagem
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 7;</code>
       */
      public Builder clearTransactionDate() {  copyOnWrite();
        instance.clearTransactionDate();
        return this;
      }

      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 8;</code>
       * @return The deviceSuid.
       */
      @java.lang.Override
      public java.lang.String getDeviceSuid() {
        return instance.getDeviceSuid();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 8;</code>
       * @return The bytes for deviceSuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceSuidBytes() {
        return instance.getDeviceSuidBytes();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 8;</code>
       * @param value The deviceSuid to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSuid(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceSuid(value);
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceSuid() {
        copyOnWrite();
        instance.clearDeviceSuid();
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 8;</code>
       * @param value The bytes for deviceSuid to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSuidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceSuidBytes(value);
        return this;
      }

      /**
       * <pre>
       *Hash da PAN do cartão utilizado
       * </pre>
       *
       * <code>bytes pan_hash = 9;</code>
       * @return The panHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPanHash() {
        return instance.getPanHash();
      }
      /**
       * <pre>
       *Hash da PAN do cartão utilizado
       * </pre>
       *
       * <code>bytes pan_hash = 9;</code>
       * @param value The panHash to set.
       * @return This builder for chaining.
       */
      public Builder setPanHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPanHash(value);
        return this;
      }
      /**
       * <pre>
       *Hash da PAN do cartão utilizado
       * </pre>
       *
       * <code>bytes pan_hash = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPanHash() {
        copyOnWrite();
        instance.clearPanHash();
        return this;
      }

      /**
       * <pre>
       *PAR do cartão utilizado (presente se informado pelo leitor)
       * </pre>
       *
       * <code>string par_card = 10;</code>
       * @return The parCard.
       */
      @java.lang.Override
      public java.lang.String getParCard() {
        return instance.getParCard();
      }
      /**
       * <pre>
       *PAR do cartão utilizado (presente se informado pelo leitor)
       * </pre>
       *
       * <code>string par_card = 10;</code>
       * @return The bytes for parCard.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParCardBytes() {
        return instance.getParCardBytes();
      }
      /**
       * <pre>
       *PAR do cartão utilizado (presente se informado pelo leitor)
       * </pre>
       *
       * <code>string par_card = 10;</code>
       * @param value The parCard to set.
       * @return This builder for chaining.
       */
      public Builder setParCard(
          java.lang.String value) {
        copyOnWrite();
        instance.setParCard(value);
        return this;
      }
      /**
       * <pre>
       *PAR do cartão utilizado (presente se informado pelo leitor)
       * </pre>
       *
       * <code>string par_card = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearParCard() {
        copyOnWrite();
        instance.clearParCard();
        return this;
      }
      /**
       * <pre>
       *PAR do cartão utilizado (presente se informado pelo leitor)
       * </pre>
       *
       * <code>string par_card = 10;</code>
       * @param value The bytes for parCard to set.
       * @return This builder for chaining.
       */
      public Builder setParCardBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParCardBytes(value);
        return this;
      }

      /**
       * <pre>
       *Dados de processamento da transação sem contato obtidos do leitor sem contato.
       * </pre>
       *
       * <code>bytes transaction_data = 11;</code>
       * @return The transactionData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTransactionData() {
        return instance.getTransactionData();
      }
      /**
       * <pre>
       *Dados de processamento da transação sem contato obtidos do leitor sem contato.
       * </pre>
       *
       * <code>bytes transaction_data = 11;</code>
       * @param value The transactionData to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTransactionData(value);
        return this;
      }
      /**
       * <pre>
       *Dados de processamento da transação sem contato obtidos do leitor sem contato.
       * </pre>
       *
       * <code>bytes transaction_data = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionData() {
        copyOnWrite();
        instance.clearTransactionData();
        return this;
      }

      /**
       * <pre>
       *Request: Versão dos parâmetros EMV para configuração do leitor.
       * </pre>
       *
       * <code>int32 emv_parameters_version = 12;</code>
       * @return The emvParametersVersion.
       */
      @java.lang.Override
      public int getEmvParametersVersion() {
        return instance.getEmvParametersVersion();
      }
      /**
       * <pre>
       *Request: Versão dos parâmetros EMV para configuração do leitor.
       * </pre>
       *
       * <code>int32 emv_parameters_version = 12;</code>
       * @param value The emvParametersVersion to set.
       * @return This builder for chaining.
       */
      public Builder setEmvParametersVersion(int value) {
        copyOnWrite();
        instance.setEmvParametersVersion(value);
        return this;
      }
      /**
       * <pre>
       *Request: Versão dos parâmetros EMV para configuração do leitor.
       * </pre>
       *
       * <code>int32 emv_parameters_version = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmvParametersVersion() {
        copyOnWrite();
        instance.clearEmvParametersVersion();
        return this;
      }

      /**
       * <pre>
       *Request: Versão das tabelas de BIN disponíveis no validador.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 13;</code>
       * @return The binParametersVersion.
       */
      @java.lang.Override
      public int getBinParametersVersion() {
        return instance.getBinParametersVersion();
      }
      /**
       * <pre>
       *Request: Versão das tabelas de BIN disponíveis no validador.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 13;</code>
       * @param value The binParametersVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBinParametersVersion(int value) {
        copyOnWrite();
        instance.setBinParametersVersion(value);
        return this;
      }
      /**
       * <pre>
       *Request: Versão das tabelas de BIN disponíveis no validador.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinParametersVersion() {
        copyOnWrite();
        instance.clearBinParametersVersion();
        return this;
      }

      /**
       * <pre>
       *Request: Versão da lista de exceção disponível no validador.
       * </pre>
       *
       * <code>int32 restriction_list_version = 14;</code>
       * @return The restrictionListVersion.
       */
      @java.lang.Override
      public int getRestrictionListVersion() {
        return instance.getRestrictionListVersion();
      }
      /**
       * <pre>
       *Request: Versão da lista de exceção disponível no validador.
       * </pre>
       *
       * <code>int32 restriction_list_version = 14;</code>
       * @param value The restrictionListVersion to set.
       * @return This builder for chaining.
       */
      public Builder setRestrictionListVersion(int value) {
        copyOnWrite();
        instance.setRestrictionListVersion(value);
        return this;
      }
      /**
       * <pre>
       *Request: Versão da lista de exceção disponível no validador.
       * </pre>
       *
       * <code>int32 restriction_list_version = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRestrictionListVersion() {
        copyOnWrite();
        instance.clearRestrictionListVersion();
        return this;
      }

      /**
       * <pre>
       *Valor da transação (presente se disponível)
       * </pre>
       *
       * <code>int32 transaction_value = 15;</code>
       * @return The transactionValue.
       */
      @java.lang.Override
      public int getTransactionValue() {
        return instance.getTransactionValue();
      }
      /**
       * <pre>
       *Valor da transação (presente se disponível)
       * </pre>
       *
       * <code>int32 transaction_value = 15;</code>
       * @param value The transactionValue to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionValue(int value) {
        copyOnWrite();
        instance.setTransactionValue(value);
        return this;
      }
      /**
       * <pre>
       *Valor da transação (presente se disponível)
       * </pre>
       *
       * <code>int32 transaction_value = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionValue() {
        copyOnWrite();
        instance.clearTransactionValue();
        return this;
      }

      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 16;</code>
       * @return The lineId.
       */
      @java.lang.Override
      public java.lang.String getLineId() {
        return instance.getLineId();
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 16;</code>
       * @return The bytes for lineId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLineIdBytes() {
        return instance.getLineIdBytes();
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 16;</code>
       * @param value The lineId to set.
       * @return This builder for chaining.
       */
      public Builder setLineId(
          java.lang.String value) {
        copyOnWrite();
        instance.setLineId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearLineId() {
        copyOnWrite();
        instance.clearLineId();
        return this;
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 16;</code>
       * @param value The bytes for lineId to set.
       * @return This builder for chaining.
       */
      public Builder setLineIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLineIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 17;</code>
       * @return The vehicleId.
       */
      @java.lang.Override
      public java.lang.String getVehicleId() {
        return instance.getVehicleId();
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 17;</code>
       * @return The bytes for vehicleId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        return instance.getVehicleIdBytes();
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 17;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(
          java.lang.String value) {
        copyOnWrite();
        instance.setVehicleId(value);
        return this;
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        copyOnWrite();
        instance.clearVehicleId();
        return this;
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 17;</code>
       * @param value The bytes for vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVehicleIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Geolocalização do validador no momento da geração da passagem
       * </pre>
       *
       * <code>string geolocation = 18;</code>
       * @return The geolocation.
       */
      @java.lang.Override
      public java.lang.String getGeolocation() {
        return instance.getGeolocation();
      }
      /**
       * <pre>
       *Geolocalização do validador no momento da geração da passagem
       * </pre>
       *
       * <code>string geolocation = 18;</code>
       * @return The bytes for geolocation.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getGeolocationBytes() {
        return instance.getGeolocationBytes();
      }
      /**
       * <pre>
       *Geolocalização do validador no momento da geração da passagem
       * </pre>
       *
       * <code>string geolocation = 18;</code>
       * @param value The geolocation to set.
       * @return This builder for chaining.
       */
      public Builder setGeolocation(
          java.lang.String value) {
        copyOnWrite();
        instance.setGeolocation(value);
        return this;
      }
      /**
       * <pre>
       *Geolocalização do validador no momento da geração da passagem
       * </pre>
       *
       * <code>string geolocation = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeolocation() {
        copyOnWrite();
        instance.clearGeolocation();
        return this;
      }
      /**
       * <pre>
       *Geolocalização do validador no momento da geração da passagem
       * </pre>
       *
       * <code>string geolocation = 18;</code>
       * @param value The bytes for geolocation to set.
       * @return This builder for chaining.
       */
      public Builder setGeolocationBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGeolocationBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.RegisterPassage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "deviceId_",
              "operatorId_",
              "readerSerialNumber_",
              "deviceSerialNumber_",
              "registerCode_",
              "passageDate_",
              "transactionDate_",
              "deviceSuid_",
              "panHash_",
              "parCard_",
              "transactionData_",
              "emvParametersVersion_",
              "binParametersVersion_",
              "restrictionListVersion_",
              "transactionValue_",
              "lineId_",
              "vehicleId_",
              "geolocation_",
            };
            java.lang.String info =
                "\u0000\u0012\u0000\u0000\u0001\u0012\u0012\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0004\u0006\t\u0007\t\b\u0208\t\n\n\u0208\u000b\n" +
                "\f\u0004\r\u0004\u000e\u0004\u000f\u0004\u0010\u0208\u0011\u0208\u0012\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.RegisterPassage)
    private static final com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage DEFAULT_INSTANCE;
    static {
      RegisterPassage defaultInstance = new RegisterPassage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RegisterPassage.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RegisterPassage> PARSER;

    public static com.google.protobuf.Parser<RegisterPassage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RegisterPassageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.RegisterPassageResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @return The gatewayUid.
     */
    java.lang.String getGatewayUid();
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @return The bytes for gatewayUid.
     */
    com.google.protobuf.ByteString
        getGatewayUidBytes();

    /**
     * <pre>
     *Response: Versão/ atual dos parâmetros
     * </pre>
     *
     * <code>int32 emv_parameters_version = 3;</code>
     * @return The emvParametersVersion.
     */
    int getEmvParametersVersion();

    /**
     * <pre>
     *Response: Versão atual das tabelas.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 4;</code>
     * @return The binParametersVersion.
     */
    int getBinParametersVersion();

    /**
     * <pre>
     *Response: Versão atual da lista de exceção.
     * </pre>
     *
     * <code>int32 restriction_list_version = 5;</code>
     * @return The restrictionListVersion.
     */
    int getRestrictionListVersion();

    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @return The deviceSuid.
     */
    java.lang.String getDeviceSuid();
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @return The bytes for deviceSuid.
     */
    com.google.protobuf.ByteString
        getDeviceSuidBytes();
  }
  /**
   * Protobuf type {@code axis.transactions.RegisterPassageResponse}
   */
  public  static final class RegisterPassageResponse extends
      com.google.protobuf.GeneratedMessageLite<
          RegisterPassageResponse, RegisterPassageResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.RegisterPassageResponse)
      RegisterPassageResponseOrBuilder {
    private RegisterPassageResponse() {
      gatewayUid_ = "";
      deviceSuid_ = "";
    }
    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @return The responseCode.
     */
    @java.lang.Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int GATEWAY_UID_FIELD_NUMBER = 2;
    private java.lang.String gatewayUid_;
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @return The gatewayUid.
     */
    @java.lang.Override
    public java.lang.String getGatewayUid() {
      return gatewayUid_;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @return The bytes for gatewayUid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGatewayUidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(gatewayUid_);
    }
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @param value The gatewayUid to set.
     */
    private void setGatewayUid(
        java.lang.String value) {
      value.getClass();
  
      gatewayUid_ = value;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     */
    private void clearGatewayUid() {
      
      gatewayUid_ = getDefaultInstance().getGatewayUid();
    }
    /**
     * <pre>
     *Número sequencial único da transação no Gateway de Mobilidade
     * </pre>
     *
     * <code>string gateway_uid = 2;</code>
     * @param value The bytes for gatewayUid to set.
     */
    private void setGatewayUidBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      gatewayUid_ = value.toStringUtf8();
      
    }

    public static final int EMV_PARAMETERS_VERSION_FIELD_NUMBER = 3;
    private int emvParametersVersion_;
    /**
     * <pre>
     *Response: Versão/ atual dos parâmetros
     * </pre>
     *
     * <code>int32 emv_parameters_version = 3;</code>
     * @return The emvParametersVersion.
     */
    @java.lang.Override
    public int getEmvParametersVersion() {
      return emvParametersVersion_;
    }
    /**
     * <pre>
     *Response: Versão/ atual dos parâmetros
     * </pre>
     *
     * <code>int32 emv_parameters_version = 3;</code>
     * @param value The emvParametersVersion to set.
     */
    private void setEmvParametersVersion(int value) {
      
      emvParametersVersion_ = value;
    }
    /**
     * <pre>
     *Response: Versão/ atual dos parâmetros
     * </pre>
     *
     * <code>int32 emv_parameters_version = 3;</code>
     */
    private void clearEmvParametersVersion() {
      
      emvParametersVersion_ = 0;
    }

    public static final int BIN_PARAMETERS_VERSION_FIELD_NUMBER = 4;
    private int binParametersVersion_;
    /**
     * <pre>
     *Response: Versão atual das tabelas.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 4;</code>
     * @return The binParametersVersion.
     */
    @java.lang.Override
    public int getBinParametersVersion() {
      return binParametersVersion_;
    }
    /**
     * <pre>
     *Response: Versão atual das tabelas.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 4;</code>
     * @param value The binParametersVersion to set.
     */
    private void setBinParametersVersion(int value) {
      
      binParametersVersion_ = value;
    }
    /**
     * <pre>
     *Response: Versão atual das tabelas.
     * </pre>
     *
     * <code>int32 bin_parameters_version = 4;</code>
     */
    private void clearBinParametersVersion() {
      
      binParametersVersion_ = 0;
    }

    public static final int RESTRICTION_LIST_VERSION_FIELD_NUMBER = 5;
    private int restrictionListVersion_;
    /**
     * <pre>
     *Response: Versão atual da lista de exceção.
     * </pre>
     *
     * <code>int32 restriction_list_version = 5;</code>
     * @return The restrictionListVersion.
     */
    @java.lang.Override
    public int getRestrictionListVersion() {
      return restrictionListVersion_;
    }
    /**
     * <pre>
     *Response: Versão atual da lista de exceção.
     * </pre>
     *
     * <code>int32 restriction_list_version = 5;</code>
     * @param value The restrictionListVersion to set.
     */
    private void setRestrictionListVersion(int value) {
      
      restrictionListVersion_ = value;
    }
    /**
     * <pre>
     *Response: Versão atual da lista de exceção.
     * </pre>
     *
     * <code>int32 restriction_list_version = 5;</code>
     */
    private void clearRestrictionListVersion() {
      
      restrictionListVersion_ = 0;
    }

    public static final int DEVICE_SUID_FIELD_NUMBER = 6;
    private java.lang.String deviceSuid_;
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @return The deviceSuid.
     */
    @java.lang.Override
    public java.lang.String getDeviceSuid() {
      return deviceSuid_;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @return The bytes for deviceSuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceSuidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceSuid_);
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @param value The deviceSuid to set.
     */
    private void setDeviceSuid(
        java.lang.String value) {
      value.getClass();
  
      deviceSuid_ = value;
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     */
    private void clearDeviceSuid() {
      
      deviceSuid_ = getDefaultInstance().getDeviceSuid();
    }
    /**
     * <pre>
     *Número sequencial único da transação no Validador
     * </pre>
     *
     * <code>string device_suid = 6;</code>
     * @param value The bytes for deviceSuid to set.
     */
    private void setDeviceSuidBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceSuid_ = value.toStringUtf8();
      
    }

    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.RegisterPassageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.RegisterPassageResponse)
        com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponseOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @return The responseCode.
       */
      @java.lang.Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <pre>
       *Número sequencial único da transação no Gateway de Mobilidade
       * </pre>
       *
       * <code>string gateway_uid = 2;</code>
       * @return The gatewayUid.
       */
      @java.lang.Override
      public java.lang.String getGatewayUid() {
        return instance.getGatewayUid();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Gateway de Mobilidade
       * </pre>
       *
       * <code>string gateway_uid = 2;</code>
       * @return The bytes for gatewayUid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getGatewayUidBytes() {
        return instance.getGatewayUidBytes();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Gateway de Mobilidade
       * </pre>
       *
       * <code>string gateway_uid = 2;</code>
       * @param value The gatewayUid to set.
       * @return This builder for chaining.
       */
      public Builder setGatewayUid(
          java.lang.String value) {
        copyOnWrite();
        instance.setGatewayUid(value);
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Gateway de Mobilidade
       * </pre>
       *
       * <code>string gateway_uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGatewayUid() {
        copyOnWrite();
        instance.clearGatewayUid();
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Gateway de Mobilidade
       * </pre>
       *
       * <code>string gateway_uid = 2;</code>
       * @param value The bytes for gatewayUid to set.
       * @return This builder for chaining.
       */
      public Builder setGatewayUidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGatewayUidBytes(value);
        return this;
      }

      /**
       * <pre>
       *Response: Versão/ atual dos parâmetros
       * </pre>
       *
       * <code>int32 emv_parameters_version = 3;</code>
       * @return The emvParametersVersion.
       */
      @java.lang.Override
      public int getEmvParametersVersion() {
        return instance.getEmvParametersVersion();
      }
      /**
       * <pre>
       *Response: Versão/ atual dos parâmetros
       * </pre>
       *
       * <code>int32 emv_parameters_version = 3;</code>
       * @param value The emvParametersVersion to set.
       * @return This builder for chaining.
       */
      public Builder setEmvParametersVersion(int value) {
        copyOnWrite();
        instance.setEmvParametersVersion(value);
        return this;
      }
      /**
       * <pre>
       *Response: Versão/ atual dos parâmetros
       * </pre>
       *
       * <code>int32 emv_parameters_version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmvParametersVersion() {
        copyOnWrite();
        instance.clearEmvParametersVersion();
        return this;
      }

      /**
       * <pre>
       *Response: Versão atual das tabelas.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 4;</code>
       * @return The binParametersVersion.
       */
      @java.lang.Override
      public int getBinParametersVersion() {
        return instance.getBinParametersVersion();
      }
      /**
       * <pre>
       *Response: Versão atual das tabelas.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 4;</code>
       * @param value The binParametersVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBinParametersVersion(int value) {
        copyOnWrite();
        instance.setBinParametersVersion(value);
        return this;
      }
      /**
       * <pre>
       *Response: Versão atual das tabelas.
       * </pre>
       *
       * <code>int32 bin_parameters_version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinParametersVersion() {
        copyOnWrite();
        instance.clearBinParametersVersion();
        return this;
      }

      /**
       * <pre>
       *Response: Versão atual da lista de exceção.
       * </pre>
       *
       * <code>int32 restriction_list_version = 5;</code>
       * @return The restrictionListVersion.
       */
      @java.lang.Override
      public int getRestrictionListVersion() {
        return instance.getRestrictionListVersion();
      }
      /**
       * <pre>
       *Response: Versão atual da lista de exceção.
       * </pre>
       *
       * <code>int32 restriction_list_version = 5;</code>
       * @param value The restrictionListVersion to set.
       * @return This builder for chaining.
       */
      public Builder setRestrictionListVersion(int value) {
        copyOnWrite();
        instance.setRestrictionListVersion(value);
        return this;
      }
      /**
       * <pre>
       *Response: Versão atual da lista de exceção.
       * </pre>
       *
       * <code>int32 restriction_list_version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRestrictionListVersion() {
        copyOnWrite();
        instance.clearRestrictionListVersion();
        return this;
      }

      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 6;</code>
       * @return The deviceSuid.
       */
      @java.lang.Override
      public java.lang.String getDeviceSuid() {
        return instance.getDeviceSuid();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 6;</code>
       * @return The bytes for deviceSuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceSuidBytes() {
        return instance.getDeviceSuidBytes();
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 6;</code>
       * @param value The deviceSuid to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSuid(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceSuid(value);
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceSuid() {
        copyOnWrite();
        instance.clearDeviceSuid();
        return this;
      }
      /**
       * <pre>
       *Número sequencial único da transação no Validador
       * </pre>
       *
       * <code>string device_suid = 6;</code>
       * @param value The bytes for deviceSuid to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSuidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceSuidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.RegisterPassageResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "responseCode_",
              "gatewayUid_",
              "emvParametersVersion_",
              "binParametersVersion_",
              "restrictionListVersion_",
              "deviceSuid_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0004\u0004\u0004\u0005\u0004\u0006\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.RegisterPassageResponse)
    private static final com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse DEFAULT_INSTANCE;
    static {
      RegisterPassageResponse defaultInstance = new RegisterPassageResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RegisterPassageResponse.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.PassageRegister.RegisterPassageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RegisterPassageResponse> PARSER;

    public static com.google.protobuf.Parser<RegisterPassageResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
