// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acceptance_list.proto

package com.axismobfintech.gpb.transactions;

public final class AcceptanceList {
  private AcceptanceList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AcceptanceListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.AcceptanceListRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The operatorId.
     */
    java.lang.String getOperatorId();
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The bytes for operatorId.
     */
    com.google.protobuf.ByteString
        getOperatorIdBytes();

    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The readerSerialNumber.
     */
    java.lang.String getReaderSerialNumber();
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The bytes for readerSerialNumber.
     */
    com.google.protobuf.ByteString
        getReaderSerialNumberBytes();

    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The deviceSerialNumber.
     */
    java.lang.String getDeviceSerialNumber();
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The bytes for deviceSerialNumber.
     */
    com.google.protobuf.ByteString
        getDeviceSerialNumberBytes();

    /**
     * <pre>
     *KSN – Key Serial Number – do leitor de cartões.
     * </pre>
     *
     * <code>bytes ksn_data = 5;</code>
     * @return The ksnData.
     */
    com.google.protobuf.ByteString getKsnData();

    /**
     * <pre>
     *Código de autorização de registro.
     * </pre>
     *
     * <code>int32 register_code = 6;</code>
     * @return The registerCode.
     */
    int getRegisterCode();

    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @return The lineId.
     */
    java.lang.String getLineId();
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @return The bytes for lineId.
     */
    com.google.protobuf.ByteString
        getLineIdBytes();

    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @return The vehicleId.
     */
    java.lang.String getVehicleId();
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @return The bytes for vehicleId.
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     * @return Whether the transactionDate field is set.
     */
    boolean hasTransactionDate();
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     * @return The transactionDate.
     */
    com.google.protobuf.Timestamp getTransactionDate();

    /**
     * <pre>
     *Versão da lista de PANs e PARs disponíveis no validador 
     * </pre>
     *
     * <code>int32 acceptance_list_version = 10;</code>
     * @return The acceptanceListVersion.
     */
    int getAcceptanceListVersion();
  }
  /**
   * Protobuf type {@code axis.transactions.AcceptanceListRequest}
   */
  public  static final class AcceptanceListRequest extends
      com.google.protobuf.GeneratedMessageLite<
          AcceptanceListRequest, AcceptanceListRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.AcceptanceListRequest)
      AcceptanceListRequestOrBuilder {
    private AcceptanceListRequest() {
      deviceId_ = "";
      operatorId_ = "";
      readerSerialNumber_ = "";
      deviceSerialNumber_ = "";
      ksnData_ = com.google.protobuf.ByteString.EMPTY;
      lineId_ = "";
      vehicleId_ = "";
    }
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.String deviceId_;
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return deviceId_;
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @param value The deviceId to set.
     */
    private void setDeviceId(
        java.lang.String value) {
      value.getClass();
  
      deviceId_ = value;
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    private void clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
    }
    /**
     * <pre>
     *Identificação do Validador.
     * </pre>
     *
     * <code>string device_id = 1;</code>
     * @param value The bytes for deviceId to set.
     */
    private void setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceId_ = value.toStringUtf8();
      
    }

    public static final int OPERATOR_ID_FIELD_NUMBER = 2;
    private java.lang.String operatorId_;
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The operatorId.
     */
    @java.lang.Override
    public java.lang.String getOperatorId() {
      return operatorId_;
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @return The bytes for operatorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperatorIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(operatorId_);
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @param value The operatorId to set.
     */
    private void setOperatorId(
        java.lang.String value) {
      value.getClass();
  
      operatorId_ = value;
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     */
    private void clearOperatorId() {
      
      operatorId_ = getDefaultInstance().getOperatorId();
    }
    /**
     * <pre>
     *Identificação da operadora de transportes.
     * </pre>
     *
     * <code>string operator_id = 2;</code>
     * @param value The bytes for operatorId to set.
     */
    private void setOperatorIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      operatorId_ = value.toStringUtf8();
      
    }

    public static final int READER_SERIAL_NUMBER_FIELD_NUMBER = 3;
    private java.lang.String readerSerialNumber_;
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The readerSerialNumber.
     */
    @java.lang.Override
    public java.lang.String getReaderSerialNumber() {
      return readerSerialNumber_;
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @return The bytes for readerSerialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReaderSerialNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(readerSerialNumber_);
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @param value The readerSerialNumber to set.
     */
    private void setReaderSerialNumber(
        java.lang.String value) {
      value.getClass();
  
      readerSerialNumber_ = value;
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     */
    private void clearReaderSerialNumber() {
      
      readerSerialNumber_ = getDefaultInstance().getReaderSerialNumber();
    }
    /**
     * <pre>
     *Número de série do leitor.
     * </pre>
     *
     * <code>string reader_serial_number = 3;</code>
     * @param value The bytes for readerSerialNumber to set.
     */
    private void setReaderSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      readerSerialNumber_ = value.toStringUtf8();
      
    }

    public static final int DEVICE_SERIAL_NUMBER_FIELD_NUMBER = 4;
    private java.lang.String deviceSerialNumber_;
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The deviceSerialNumber.
     */
    @java.lang.Override
    public java.lang.String getDeviceSerialNumber() {
      return deviceSerialNumber_;
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @return The bytes for deviceSerialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceSerialNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceSerialNumber_);
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @param value The deviceSerialNumber to set.
     */
    private void setDeviceSerialNumber(
        java.lang.String value) {
      value.getClass();
  
      deviceSerialNumber_ = value;
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     */
    private void clearDeviceSerialNumber() {
      
      deviceSerialNumber_ = getDefaultInstance().getDeviceSerialNumber();
    }
    /**
     * <pre>
     *Número de série do Validador.
     * </pre>
     *
     * <code>string device_serial_number = 4;</code>
     * @param value The bytes for deviceSerialNumber to set.
     */
    private void setDeviceSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceSerialNumber_ = value.toStringUtf8();
      
    }

    public static final int KSN_DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString ksnData_;
    /**
     * <pre>
     *KSN – Key Serial Number – do leitor de cartões.
     * </pre>
     *
     * <code>bytes ksn_data = 5;</code>
     * @return The ksnData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKsnData() {
      return ksnData_;
    }
    /**
     * <pre>
     *KSN – Key Serial Number – do leitor de cartões.
     * </pre>
     *
     * <code>bytes ksn_data = 5;</code>
     * @param value The ksnData to set.
     */
    private void setKsnData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      ksnData_ = value;
    }
    /**
     * <pre>
     *KSN – Key Serial Number – do leitor de cartões.
     * </pre>
     *
     * <code>bytes ksn_data = 5;</code>
     */
    private void clearKsnData() {
      
      ksnData_ = getDefaultInstance().getKsnData();
    }

    public static final int REGISTER_CODE_FIELD_NUMBER = 6;
    private int registerCode_;
    /**
     * <pre>
     *Código de autorização de registro.
     * </pre>
     *
     * <code>int32 register_code = 6;</code>
     * @return The registerCode.
     */
    @java.lang.Override
    public int getRegisterCode() {
      return registerCode_;
    }
    /**
     * <pre>
     *Código de autorização de registro.
     * </pre>
     *
     * <code>int32 register_code = 6;</code>
     * @param value The registerCode to set.
     */
    private void setRegisterCode(int value) {
      
      registerCode_ = value;
    }
    /**
     * <pre>
     *Código de autorização de registro.
     * </pre>
     *
     * <code>int32 register_code = 6;</code>
     */
    private void clearRegisterCode() {
      
      registerCode_ = 0;
    }

    public static final int LINE_ID_FIELD_NUMBER = 7;
    private java.lang.String lineId_;
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @return The lineId.
     */
    @java.lang.Override
    public java.lang.String getLineId() {
      return lineId_;
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @return The bytes for lineId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLineIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lineId_);
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @param value The lineId to set.
     */
    private void setLineId(
        java.lang.String value) {
      value.getClass();
  
      lineId_ = value;
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     */
    private void clearLineId() {
      
      lineId_ = getDefaultInstance().getLineId();
    }
    /**
     * <pre>
     *Identificação da linha/viagem (presente se disponível no momento do registro).
     * </pre>
     *
     * <code>string line_id = 7;</code>
     * @param value The bytes for lineId to set.
     */
    private void setLineIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lineId_ = value.toStringUtf8();
      
    }

    public static final int VEHICLE_ID_FIELD_NUMBER = 8;
    private java.lang.String vehicleId_;
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @return The vehicleId.
     */
    @java.lang.Override
    public java.lang.String getVehicleId() {
      return vehicleId_;
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @return The bytes for vehicleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(vehicleId_);
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @param value The vehicleId to set.
     */
    private void setVehicleId(
        java.lang.String value) {
      value.getClass();
  
      vehicleId_ = value;
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     */
    private void clearVehicleId() {
      
      vehicleId_ = getDefaultInstance().getVehicleId();
    }
    /**
     * <pre>
     *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
     * </pre>
     *
     * <code>string vehicle_id = 8;</code>
     * @param value The bytes for vehicleId to set.
     */
    private void setVehicleIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      vehicleId_ = value.toStringUtf8();
      
    }

    public static final int TRANSACTION_DATE_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp transactionDate_;
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     */
    @java.lang.Override
    public boolean hasTransactionDate() {
      return transactionDate_ != null;
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTransactionDate() {
      return transactionDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : transactionDate_;
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     */
    private void setTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  transactionDate_ = value;
      
      }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (transactionDate_ != null &&
          transactionDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        transactionDate_ =
          com.google.protobuf.Timestamp.newBuilder(transactionDate_).mergeFrom(value).buildPartial();
      } else {
        transactionDate_ = value;
      }
      
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
     */
    private void clearTransactionDate() {  transactionDate_ = null;
      
    }

    public static final int ACCEPTANCE_LIST_VERSION_FIELD_NUMBER = 10;
    private int acceptanceListVersion_;
    /**
     * <pre>
     *Versão da lista de PANs e PARs disponíveis no validador 
     * </pre>
     *
     * <code>int32 acceptance_list_version = 10;</code>
     * @return The acceptanceListVersion.
     */
    @java.lang.Override
    public int getAcceptanceListVersion() {
      return acceptanceListVersion_;
    }
    /**
     * <pre>
     *Versão da lista de PANs e PARs disponíveis no validador 
     * </pre>
     *
     * <code>int32 acceptance_list_version = 10;</code>
     * @param value The acceptanceListVersion to set.
     */
    private void setAcceptanceListVersion(int value) {
      
      acceptanceListVersion_ = value;
    }
    /**
     * <pre>
     *Versão da lista de PANs e PARs disponíveis no validador 
     * </pre>
     *
     * <code>int32 acceptance_list_version = 10;</code>
     */
    private void clearAcceptanceListVersion() {
      
      acceptanceListVersion_ = 0;
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.AcceptanceListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.AcceptanceListRequest)
        com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequestOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return The deviceId.
       */
      @java.lang.Override
      public java.lang.String getDeviceId() {
        return instance.getDeviceId();
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return The bytes for deviceId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        return instance.getDeviceIdBytes();
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        copyOnWrite();
        instance.clearDeviceId();
        return this;
      }
      /**
       * <pre>
       *Identificação do Validador.
       * </pre>
       *
       * <code>string device_id = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return The operatorId.
       */
      @java.lang.Override
      public java.lang.String getOperatorId() {
        return instance.getOperatorId();
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return The bytes for operatorId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOperatorIdBytes() {
        return instance.getOperatorIdBytes();
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @param value The operatorId to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOperatorId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperatorId() {
        copyOnWrite();
        instance.clearOperatorId();
        return this;
      }
      /**
       * <pre>
       *Identificação da operadora de transportes.
       * </pre>
       *
       * <code>string operator_id = 2;</code>
       * @param value The bytes for operatorId to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOperatorIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return The readerSerialNumber.
       */
      @java.lang.Override
      public java.lang.String getReaderSerialNumber() {
        return instance.getReaderSerialNumber();
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return The bytes for readerSerialNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReaderSerialNumberBytes() {
        return instance.getReaderSerialNumberBytes();
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @param value The readerSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReaderSerialNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setReaderSerialNumber(value);
        return this;
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReaderSerialNumber() {
        copyOnWrite();
        instance.clearReaderSerialNumber();
        return this;
      }
      /**
       * <pre>
       *Número de série do leitor.
       * </pre>
       *
       * <code>string reader_serial_number = 3;</code>
       * @param value The bytes for readerSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReaderSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReaderSerialNumberBytes(value);
        return this;
      }

      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return The deviceSerialNumber.
       */
      @java.lang.Override
      public java.lang.String getDeviceSerialNumber() {
        return instance.getDeviceSerialNumber();
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return The bytes for deviceSerialNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceSerialNumberBytes() {
        return instance.getDeviceSerialNumberBytes();
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @param value The deviceSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSerialNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceSerialNumber(value);
        return this;
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceSerialNumber() {
        copyOnWrite();
        instance.clearDeviceSerialNumber();
        return this;
      }
      /**
       * <pre>
       *Número de série do Validador.
       * </pre>
       *
       * <code>string device_serial_number = 4;</code>
       * @param value The bytes for deviceSerialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceSerialNumberBytes(value);
        return this;
      }

      /**
       * <pre>
       *KSN – Key Serial Number – do leitor de cartões.
       * </pre>
       *
       * <code>bytes ksn_data = 5;</code>
       * @return The ksnData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKsnData() {
        return instance.getKsnData();
      }
      /**
       * <pre>
       *KSN – Key Serial Number – do leitor de cartões.
       * </pre>
       *
       * <code>bytes ksn_data = 5;</code>
       * @param value The ksnData to set.
       * @return This builder for chaining.
       */
      public Builder setKsnData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKsnData(value);
        return this;
      }
      /**
       * <pre>
       *KSN – Key Serial Number – do leitor de cartões.
       * </pre>
       *
       * <code>bytes ksn_data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearKsnData() {
        copyOnWrite();
        instance.clearKsnData();
        return this;
      }

      /**
       * <pre>
       *Código de autorização de registro.
       * </pre>
       *
       * <code>int32 register_code = 6;</code>
       * @return The registerCode.
       */
      @java.lang.Override
      public int getRegisterCode() {
        return instance.getRegisterCode();
      }
      /**
       * <pre>
       *Código de autorização de registro.
       * </pre>
       *
       * <code>int32 register_code = 6;</code>
       * @param value The registerCode to set.
       * @return This builder for chaining.
       */
      public Builder setRegisterCode(int value) {
        copyOnWrite();
        instance.setRegisterCode(value);
        return this;
      }
      /**
       * <pre>
       *Código de autorização de registro.
       * </pre>
       *
       * <code>int32 register_code = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegisterCode() {
        copyOnWrite();
        instance.clearRegisterCode();
        return this;
      }

      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 7;</code>
       * @return The lineId.
       */
      @java.lang.Override
      public java.lang.String getLineId() {
        return instance.getLineId();
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 7;</code>
       * @return The bytes for lineId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLineIdBytes() {
        return instance.getLineIdBytes();
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 7;</code>
       * @param value The lineId to set.
       * @return This builder for chaining.
       */
      public Builder setLineId(
          java.lang.String value) {
        copyOnWrite();
        instance.setLineId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLineId() {
        copyOnWrite();
        instance.clearLineId();
        return this;
      }
      /**
       * <pre>
       *Identificação da linha/viagem (presente se disponível no momento do registro).
       * </pre>
       *
       * <code>string line_id = 7;</code>
       * @param value The bytes for lineId to set.
       * @return This builder for chaining.
       */
      public Builder setLineIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLineIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 8;</code>
       * @return The vehicleId.
       */
      @java.lang.Override
      public java.lang.String getVehicleId() {
        return instance.getVehicleId();
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 8;</code>
       * @return The bytes for vehicleId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        return instance.getVehicleIdBytes();
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 8;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(
          java.lang.String value) {
        copyOnWrite();
        instance.setVehicleId(value);
        return this;
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        copyOnWrite();
        instance.clearVehicleId();
        return this;
      }
      /**
       * <pre>
       *Identificador do veículo em que a transação foi realizada (presente se disponível no momento do registro.
       * </pre>
       *
       * <code>string vehicle_id = 8;</code>
       * @param value The bytes for vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVehicleIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      @java.lang.Override
      public boolean hasTransactionDate() {
        return instance.hasTransactionDate();
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getTransactionDate() {
        return instance.getTransactionDate();
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      public Builder setTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setTransactionDate(value);
        return this;
        }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      public Builder setTransactionDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setTransactionDate(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      public Builder mergeTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeTransactionDate(value);
        return this;
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 9;</code>
       */
      public Builder clearTransactionDate() {  copyOnWrite();
        instance.clearTransactionDate();
        return this;
      }

      /**
       * <pre>
       *Versão da lista de PANs e PARs disponíveis no validador 
       * </pre>
       *
       * <code>int32 acceptance_list_version = 10;</code>
       * @return The acceptanceListVersion.
       */
      @java.lang.Override
      public int getAcceptanceListVersion() {
        return instance.getAcceptanceListVersion();
      }
      /**
       * <pre>
       *Versão da lista de PANs e PARs disponíveis no validador 
       * </pre>
       *
       * <code>int32 acceptance_list_version = 10;</code>
       * @param value The acceptanceListVersion to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptanceListVersion(int value) {
        copyOnWrite();
        instance.setAcceptanceListVersion(value);
        return this;
      }
      /**
       * <pre>
       *Versão da lista de PANs e PARs disponíveis no validador 
       * </pre>
       *
       * <code>int32 acceptance_list_version = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptanceListVersion() {
        copyOnWrite();
        instance.clearAcceptanceListVersion();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.AcceptanceListRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "deviceId_",
              "operatorId_",
              "readerSerialNumber_",
              "deviceSerialNumber_",
              "ksnData_",
              "registerCode_",
              "lineId_",
              "vehicleId_",
              "transactionDate_",
              "acceptanceListVersion_",
            };
            java.lang.String info =
                "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
                "\u0004\u0208\u0005\n\u0006\u0004\u0007\u0208\b\u0208\t\t\n\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.AcceptanceListRequest)
    private static final com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest DEFAULT_INSTANCE;
    static {
      AcceptanceListRequest defaultInstance = new AcceptanceListRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AcceptanceListRequest.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AcceptanceListRequest> PARSER;

    public static com.google.protobuf.Parser<AcceptanceListRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AcceptanceListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.AcceptanceListResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <pre>
     *Versão atual da lista de PANs e PARs.
     * </pre>
     *
     * <code>int32 acceptance_list_version = 2;</code>
     * @return The acceptanceListVersion.
     */
    int getAcceptanceListVersion();

    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    java.util.List<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> 
        getAcceptanceListList();
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation getAcceptanceList(int index);
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    int getAcceptanceListCount();

    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     * @return Whether the transactionDate field is set.
     */
    boolean hasTransactionDate();
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     * @return The transactionDate.
     */
    com.google.protobuf.Timestamp getTransactionDate();
  }
  /**
   * Protobuf type {@code axis.transactions.AcceptanceListResponse}
   */
  public  static final class AcceptanceListResponse extends
      com.google.protobuf.GeneratedMessageLite<
          AcceptanceListResponse, AcceptanceListResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.AcceptanceListResponse)
      AcceptanceListResponseOrBuilder {
    private AcceptanceListResponse() {
      acceptanceList_ = emptyProtobufList();
    }
    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @return The responseCode.
     */
    @java.lang.Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <pre>
     *Código de resposta da solicitação.
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int ACCEPTANCE_LIST_VERSION_FIELD_NUMBER = 2;
    private int acceptanceListVersion_;
    /**
     * <pre>
     *Versão atual da lista de PANs e PARs.
     * </pre>
     *
     * <code>int32 acceptance_list_version = 2;</code>
     * @return The acceptanceListVersion.
     */
    @java.lang.Override
    public int getAcceptanceListVersion() {
      return acceptanceListVersion_;
    }
    /**
     * <pre>
     *Versão atual da lista de PANs e PARs.
     * </pre>
     *
     * <code>int32 acceptance_list_version = 2;</code>
     * @param value The acceptanceListVersion to set.
     */
    private void setAcceptanceListVersion(int value) {
      
      acceptanceListVersion_ = value;
    }
    /**
     * <pre>
     *Versão atual da lista de PANs e PARs.
     * </pre>
     *
     * <code>int32 acceptance_list_version = 2;</code>
     */
    private void clearAcceptanceListVersion() {
      
      acceptanceListVersion_ = 0;
    }

    public static final int ACCEPTANCE_LIST_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> acceptanceList_;
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> getAcceptanceListList() {
      return acceptanceList_;
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    public java.util.List<? extends com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformationOrBuilder> 
        getAcceptanceListOrBuilderList() {
      return acceptanceList_;
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    @java.lang.Override
    public int getAcceptanceListCount() {
      return acceptanceList_.size();
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation getAcceptanceList(int index) {
      return acceptanceList_.get(index);
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    public com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformationOrBuilder getAcceptanceListOrBuilder(
        int index) {
      return acceptanceList_.get(index);
    }
    private void ensureAcceptanceListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> tmp = acceptanceList_;
      if (!tmp.isModifiable()) {
        acceptanceList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void setAcceptanceList(
        int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
      value.getClass();
  ensureAcceptanceListIsMutable();
      acceptanceList_.set(index, value);
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void addAcceptanceList(com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
      value.getClass();
  ensureAcceptanceListIsMutable();
      acceptanceList_.add(value);
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void addAcceptanceList(
        int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
      value.getClass();
  ensureAcceptanceListIsMutable();
      acceptanceList_.add(index, value);
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void addAllAcceptanceList(
        java.lang.Iterable<? extends com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> values) {
      ensureAcceptanceListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, acceptanceList_);
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void clearAcceptanceList() {
      acceptanceList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
     */
    private void removeAcceptanceList(int index) {
      ensureAcceptanceListIsMutable();
      acceptanceList_.remove(index);
    }

    public static final int TRANSACTION_DATE_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp transactionDate_;
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     */
    @java.lang.Override
    public boolean hasTransactionDate() {
      return transactionDate_ != null;
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTransactionDate() {
      return transactionDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : transactionDate_;
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     */
    private void setTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  transactionDate_ = value;
      
      }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTransactionDate(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (transactionDate_ != null &&
          transactionDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        transactionDate_ =
          com.google.protobuf.Timestamp.newBuilder(transactionDate_).mergeFrom(value).buildPartial();
      } else {
        transactionDate_ = value;
      }
      
    }
    /**
     * <pre>
     *Data e hora de envio da transação ao Gateway 
     * </pre>
     *
     * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
     */
    private void clearTransactionDate() {  transactionDate_ = null;
      
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.AcceptanceListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.AcceptanceListResponse)
        com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponseOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @return The responseCode.
       */
      @java.lang.Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <pre>
       *Código de resposta da solicitação.
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <pre>
       *Versão atual da lista de PANs e PARs.
       * </pre>
       *
       * <code>int32 acceptance_list_version = 2;</code>
       * @return The acceptanceListVersion.
       */
      @java.lang.Override
      public int getAcceptanceListVersion() {
        return instance.getAcceptanceListVersion();
      }
      /**
       * <pre>
       *Versão atual da lista de PANs e PARs.
       * </pre>
       *
       * <code>int32 acceptance_list_version = 2;</code>
       * @param value The acceptanceListVersion to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptanceListVersion(int value) {
        copyOnWrite();
        instance.setAcceptanceListVersion(value);
        return this;
      }
      /**
       * <pre>
       *Versão atual da lista de PANs e PARs.
       * </pre>
       *
       * <code>int32 acceptance_list_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptanceListVersion() {
        copyOnWrite();
        instance.clearAcceptanceListVersion();
        return this;
      }

      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> getAcceptanceListList() {
        return java.util.Collections.unmodifiableList(
            instance.getAcceptanceListList());
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      @java.lang.Override
      public int getAcceptanceListCount() {
        return instance.getAcceptanceListCount();
      }/**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation getAcceptanceList(int index) {
        return instance.getAcceptanceList(index);
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder setAcceptanceList(
          int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
        copyOnWrite();
        instance.setAcceptanceList(index, value);
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder setAcceptanceList(
          int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.Builder builderForValue) {
        copyOnWrite();
        instance.setAcceptanceList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder addAcceptanceList(com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
        copyOnWrite();
        instance.addAcceptanceList(value);
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder addAcceptanceList(
          int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation value) {
        copyOnWrite();
        instance.addAcceptanceList(index, value);
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder addAcceptanceList(
          com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.Builder builderForValue) {
        copyOnWrite();
        instance.addAcceptanceList(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder addAcceptanceList(
          int index, com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.Builder builderForValue) {
        copyOnWrite();
        instance.addAcceptanceList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder addAllAcceptanceList(
          java.lang.Iterable<? extends com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> values) {
        copyOnWrite();
        instance.addAllAcceptanceList(values);
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder clearAcceptanceList() {
        copyOnWrite();
        instance.clearAcceptanceList();
        return this;
      }
      /**
       * <code>repeated .axis.transactions.AcceptanceListCardInformation acceptance_list = 3;</code>
       */
      public Builder removeAcceptanceList(int index) {
        copyOnWrite();
        instance.removeAcceptanceList(index);
        return this;
      }

      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      @java.lang.Override
      public boolean hasTransactionDate() {
        return instance.hasTransactionDate();
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getTransactionDate() {
        return instance.getTransactionDate();
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      public Builder setTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setTransactionDate(value);
        return this;
        }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      public Builder setTransactionDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setTransactionDate(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      public Builder mergeTransactionDate(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeTransactionDate(value);
        return this;
      }
      /**
       * <pre>
       *Data e hora de envio da transação ao Gateway 
       * </pre>
       *
       * <code>.google.protobuf.Timestamp transaction_date = 4;</code>
       */
      public Builder clearTransactionDate() {  copyOnWrite();
        instance.clearTransactionDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.AcceptanceListResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "responseCode_",
              "acceptanceListVersion_",
              "acceptanceList_",
              com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.class,
              "transactionDate_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u001b\u0004\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.AcceptanceListResponse)
    private static final com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse DEFAULT_INSTANCE;
    static {
      AcceptanceListResponse defaultInstance = new AcceptanceListResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AcceptanceListResponse.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AcceptanceListResponse> PARSER;

    public static com.google.protobuf.Parser<AcceptanceListResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AcceptanceListCardInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.AcceptanceListCardInformation)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     * @return Whether the panList field is set.
     */
    boolean hasPanList();
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     * @return The panList.
     */
    com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList getPanList();

    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     * @return Whether the parList field is set.
     */
    boolean hasParList();
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     * @return The parList.
     */
    com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList getParList();

    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @return The action.
     */
    com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction getAction();
  }
  /**
   * Protobuf type {@code axis.transactions.AcceptanceListCardInformation}
   */
  public  static final class AcceptanceListCardInformation extends
      com.google.protobuf.GeneratedMessageLite<
          AcceptanceListCardInformation, AcceptanceListCardInformation.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.AcceptanceListCardInformation)
      AcceptanceListCardInformationOrBuilder {
    private AcceptanceListCardInformation() {
    }
    public static final int PAN_LIST_FIELD_NUMBER = 1;
    private com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList panList_;
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     */
    @java.lang.Override
    public boolean hasPanList() {
      return panList_ != null;
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList getPanList() {
      return panList_ == null ? com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList.getDefaultInstance() : panList_;
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     */
    private void setPanList(com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList value) {
      value.getClass();
  panList_ = value;
      
      }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergePanList(com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList value) {
      value.getClass();
  if (panList_ != null &&
          panList_ != com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList.getDefaultInstance()) {
        panList_ =
          com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList.newBuilder(panList_).mergeFrom(value).buildPartial();
      } else {
        panList_ = value;
      }
      
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
     */
    private void clearPanList() {  panList_ = null;
      
    }

    public static final int PAR_LIST_FIELD_NUMBER = 2;
    private com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList parList_;
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     */
    @java.lang.Override
    public boolean hasParList() {
      return parList_ != null;
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList getParList() {
      return parList_ == null ? com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList.getDefaultInstance() : parList_;
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     */
    private void setParList(com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList value) {
      value.getClass();
  parList_ = value;
      
      }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeParList(com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList value) {
      value.getClass();
  if (parList_ != null &&
          parList_ != com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList.getDefaultInstance()) {
        parList_ =
          com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList.newBuilder(parList_).mergeFrom(value).buildPartial();
      } else {
        parList_ = value;
      }
      
    }
    /**
     * <pre>
     *((Presente se houver atualização e a solicitação foi autorizada).
     * </pre>
     *
     * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
     */
    private void clearParList() {  parList_ = null;
      
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private int action_;
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override
    public int getActionValue() {
      return action_;
    }
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction getAction() {
      com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction result = com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction.forNumber(action_);
      return result == null ? com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @param value The enum numeric value on the wire for action to set.
     */
    private void setActionValue(int value) {
        action_ = value;
    }
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     * @param value The action to set.
     */
    private void setAction(com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction value) {
      action_ = value.getNumber();
      
    }
    /**
     * <pre>
     *Acao
     * </pre>
     *
     * <code>.axis.transactions.CardAction action = 3;</code>
     */
    private void clearAction() {
      
      action_ = 0;
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.AcceptanceListCardInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.AcceptanceListCardInformation)
        com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformationOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      @java.lang.Override
      public boolean hasPanList() {
        return instance.hasPanList();
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList getPanList() {
        return instance.getPanList();
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      public Builder setPanList(com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList value) {
        copyOnWrite();
        instance.setPanList(value);
        return this;
        }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      public Builder setPanList(
          com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList.Builder builderForValue) {
        copyOnWrite();
        instance.setPanList(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      public Builder mergePanList(com.axismobfintech.gpb.transactions.PanAcceptanceList.PrimaryAccountNumberWhiteList value) {
        copyOnWrite();
        instance.mergePanList(value);
        return this;
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountNumberWhiteList pan_list = 1;</code>
       */
      public Builder clearPanList() {  copyOnWrite();
        instance.clearPanList();
        return this;
      }

      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      @java.lang.Override
      public boolean hasParList() {
        return instance.hasParList();
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList getParList() {
        return instance.getParList();
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      public Builder setParList(com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList value) {
        copyOnWrite();
        instance.setParList(value);
        return this;
        }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      public Builder setParList(
          com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList.Builder builderForValue) {
        copyOnWrite();
        instance.setParList(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      public Builder mergeParList(com.axismobfintech.gpb.transactions.ParAcceptanceList.PrimaryAccountReferenceWhiteList value) {
        copyOnWrite();
        instance.mergeParList(value);
        return this;
      }
      /**
       * <pre>
       *((Presente se houver atualização e a solicitação foi autorizada).
       * </pre>
       *
       * <code>.axis.transactions.PrimaryAccountReferenceWhiteList par_list = 2;</code>
       */
      public Builder clearParList() {  copyOnWrite();
        instance.clearParList();
        return this;
      }

      /**
       * <pre>
       *Acao
       * </pre>
       *
       * <code>.axis.transactions.CardAction action = 3;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override
      public int getActionValue() {
        return instance.getActionValue();
      }
      /**
       * <pre>
       *Acao
       * </pre>
       *
       * <code>.axis.transactions.CardAction action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        copyOnWrite();
        instance.setActionValue(value);
        return this;
      }
      /**
       * <pre>
       *Acao
       * </pre>
       *
       * <code>.axis.transactions.CardAction action = 3;</code>
       * @return The action.
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction getAction() {
        return instance.getAction();
      }
      /**
       * <pre>
       *Acao
       * </pre>
       *
       * <code>.axis.transactions.CardAction action = 3;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(com.axismobfintech.gpb.transactions.CardActionOuterClass.CardAction value) {
        copyOnWrite();
        instance.setAction(value);
        return this;
      }
      /**
       * <pre>
       *Acao
       * </pre>
       *
       * <code>.axis.transactions.CardAction action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        copyOnWrite();
        instance.clearAction();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.AcceptanceListCardInformation)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "panList_",
              "parList_",
              "action_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
                "\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.AcceptanceListCardInformation)
    private static final com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation DEFAULT_INSTANCE;
    static {
      AcceptanceListCardInformation defaultInstance = new AcceptanceListCardInformation();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AcceptanceListCardInformation.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.AcceptanceList.AcceptanceListCardInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AcceptanceListCardInformation> PARSER;

    public static com.google.protobuf.Parser<AcceptanceListCardInformation> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
