// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protos/accepted_bin.proto

package com.axismobfintech.gpb.transactions;

public final class AcceptedBin {
  private AcceptedBin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AcceptedBankIdentificationNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.AcceptedBankIdentificationNumber)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Identificação da tabela AID (fixo �03�)
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <pre>
     *índice do registro na tabela (0001 - 9999)
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <pre>
     *Código de identifica��o do emissor.
     * </pre>
     *
     * <code>int32 issuer_code = 3;</code>
     * @return The issuerCode.
     */
    int getIssuerCode();

    /**
     * <pre>
     *Número inicial da faixa
     * </pre>
     *
     * <code>uint64 initial_range = 4;</code>
     * @return The initialRange.
     */
    long getInitialRange();

    /**
     * <pre>
     *Número final da faixa
     * </pre>
     *
     * <code>uint64 final_range = 5;</code>
     * @return The finalRange.
     */
    long getFinalRange();

    /**
     * <pre>
     *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
     * </pre>
     *
     * <code>uint32 total_sequential_transactions_allowed = 6;</code>
     * @return The totalSequentialTransactionsAllowed.
     */
    int getTotalSequentialTransactionsAllowed();
  }
  /**
   * Protobuf type {@code axis.transactions.AcceptedBankIdentificationNumber}
   */
  public  static final class AcceptedBankIdentificationNumber extends
      com.google.protobuf.GeneratedMessageLite<
          AcceptedBankIdentificationNumber, AcceptedBankIdentificationNumber.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.AcceptedBankIdentificationNumber)
      AcceptedBankIdentificationNumberOrBuilder {
    private AcceptedBankIdentificationNumber() {
    }
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <pre>
     *Identificação da tabela AID (fixo �03�)
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     *Identificação da tabela AID (fixo �03�)
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     * @param value The messageId to set.
     */
    private void setMessageId(int value) {
      
      messageId_ = value;
    }
    /**
     * <pre>
     *Identificação da tabela AID (fixo �03�)
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     */
    private void clearMessageId() {
      
      messageId_ = 0;
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private int index_;
    /**
     * <pre>
     *índice do registro na tabela (0001 - 9999)
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     *índice do registro na tabela (0001 - 9999)
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <pre>
     *índice do registro na tabela (0001 - 9999)
     * </pre>
     *
     * <code>int32 index = 2;</code>
     */
    private void clearIndex() {
      
      index_ = 0;
    }

    public static final int ISSUER_CODE_FIELD_NUMBER = 3;
    private int issuerCode_;
    /**
     * <pre>
     *Código de identifica��o do emissor.
     * </pre>
     *
     * <code>int32 issuer_code = 3;</code>
     * @return The issuerCode.
     */
    @java.lang.Override
    public int getIssuerCode() {
      return issuerCode_;
    }
    /**
     * <pre>
     *Código de identifica��o do emissor.
     * </pre>
     *
     * <code>int32 issuer_code = 3;</code>
     * @param value The issuerCode to set.
     */
    private void setIssuerCode(int value) {
      
      issuerCode_ = value;
    }
    /**
     * <pre>
     *Código de identifica��o do emissor.
     * </pre>
     *
     * <code>int32 issuer_code = 3;</code>
     */
    private void clearIssuerCode() {
      
      issuerCode_ = 0;
    }

    public static final int INITIAL_RANGE_FIELD_NUMBER = 4;
    private long initialRange_;
    /**
     * <pre>
     *Número inicial da faixa
     * </pre>
     *
     * <code>uint64 initial_range = 4;</code>
     * @return The initialRange.
     */
    @java.lang.Override
    public long getInitialRange() {
      return initialRange_;
    }
    /**
     * <pre>
     *Número inicial da faixa
     * </pre>
     *
     * <code>uint64 initial_range = 4;</code>
     * @param value The initialRange to set.
     */
    private void setInitialRange(long value) {
      
      initialRange_ = value;
    }
    /**
     * <pre>
     *Número inicial da faixa
     * </pre>
     *
     * <code>uint64 initial_range = 4;</code>
     */
    private void clearInitialRange() {
      
      initialRange_ = 0L;
    }

    public static final int FINAL_RANGE_FIELD_NUMBER = 5;
    private long finalRange_;
    /**
     * <pre>
     *Número final da faixa
     * </pre>
     *
     * <code>uint64 final_range = 5;</code>
     * @return The finalRange.
     */
    @java.lang.Override
    public long getFinalRange() {
      return finalRange_;
    }
    /**
     * <pre>
     *Número final da faixa
     * </pre>
     *
     * <code>uint64 final_range = 5;</code>
     * @param value The finalRange to set.
     */
    private void setFinalRange(long value) {
      
      finalRange_ = value;
    }
    /**
     * <pre>
     *Número final da faixa
     * </pre>
     *
     * <code>uint64 final_range = 5;</code>
     */
    private void clearFinalRange() {
      
      finalRange_ = 0L;
    }

    public static final int TOTAL_SEQUENTIAL_TRANSACTIONS_ALLOWED_FIELD_NUMBER = 6;
    private int totalSequentialTransactionsAllowed_;
    /**
     * <pre>
     *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
     * </pre>
     *
     * <code>uint32 total_sequential_transactions_allowed = 6;</code>
     * @return The totalSequentialTransactionsAllowed.
     */
    @java.lang.Override
    public int getTotalSequentialTransactionsAllowed() {
      return totalSequentialTransactionsAllowed_;
    }
    /**
     * <pre>
     *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
     * </pre>
     *
     * <code>uint32 total_sequential_transactions_allowed = 6;</code>
     * @param value The totalSequentialTransactionsAllowed to set.
     */
    private void setTotalSequentialTransactionsAllowed(int value) {
      
      totalSequentialTransactionsAllowed_ = value;
    }
    /**
     * <pre>
     *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
     * </pre>
     *
     * <code>uint32 total_sequential_transactions_allowed = 6;</code>
     */
    private void clearTotalSequentialTransactionsAllowed() {
      
      totalSequentialTransactionsAllowed_ = 0;
    }

    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.AcceptedBankIdentificationNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.AcceptedBankIdentificationNumber)
        com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumberOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Identificação da tabela AID (fixo �03�)
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return instance.getMessageId();
      }
      /**
       * <pre>
       *Identificação da tabela AID (fixo �03�)
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        copyOnWrite();
        instance.setMessageId(value);
        return this;
      }
      /**
       * <pre>
       *Identificação da tabela AID (fixo �03�)
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        copyOnWrite();
        instance.clearMessageId();
        return this;
      }

      /**
       * <pre>
       *índice do registro na tabela (0001 - 9999)
       * </pre>
       *
       * <code>int32 index = 2;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <pre>
       *índice do registro na tabela (0001 - 9999)
       * </pre>
       *
       * <code>int32 index = 2;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <pre>
       *índice do registro na tabela (0001 - 9999)
       * </pre>
       *
       * <code>int32 index = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      /**
       * <pre>
       *Código de identifica��o do emissor.
       * </pre>
       *
       * <code>int32 issuer_code = 3;</code>
       * @return The issuerCode.
       */
      @java.lang.Override
      public int getIssuerCode() {
        return instance.getIssuerCode();
      }
      /**
       * <pre>
       *Código de identifica��o do emissor.
       * </pre>
       *
       * <code>int32 issuer_code = 3;</code>
       * @param value The issuerCode to set.
       * @return This builder for chaining.
       */
      public Builder setIssuerCode(int value) {
        copyOnWrite();
        instance.setIssuerCode(value);
        return this;
      }
      /**
       * <pre>
       *Código de identifica��o do emissor.
       * </pre>
       *
       * <code>int32 issuer_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuerCode() {
        copyOnWrite();
        instance.clearIssuerCode();
        return this;
      }

      /**
       * <pre>
       *Número inicial da faixa
       * </pre>
       *
       * <code>uint64 initial_range = 4;</code>
       * @return The initialRange.
       */
      @java.lang.Override
      public long getInitialRange() {
        return instance.getInitialRange();
      }
      /**
       * <pre>
       *Número inicial da faixa
       * </pre>
       *
       * <code>uint64 initial_range = 4;</code>
       * @param value The initialRange to set.
       * @return This builder for chaining.
       */
      public Builder setInitialRange(long value) {
        copyOnWrite();
        instance.setInitialRange(value);
        return this;
      }
      /**
       * <pre>
       *Número inicial da faixa
       * </pre>
       *
       * <code>uint64 initial_range = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitialRange() {
        copyOnWrite();
        instance.clearInitialRange();
        return this;
      }

      /**
       * <pre>
       *Número final da faixa
       * </pre>
       *
       * <code>uint64 final_range = 5;</code>
       * @return The finalRange.
       */
      @java.lang.Override
      public long getFinalRange() {
        return instance.getFinalRange();
      }
      /**
       * <pre>
       *Número final da faixa
       * </pre>
       *
       * <code>uint64 final_range = 5;</code>
       * @param value The finalRange to set.
       * @return This builder for chaining.
       */
      public Builder setFinalRange(long value) {
        copyOnWrite();
        instance.setFinalRange(value);
        return this;
      }
      /**
       * <pre>
       *Número final da faixa
       * </pre>
       *
       * <code>uint64 final_range = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalRange() {
        copyOnWrite();
        instance.clearFinalRange();
        return this;
      }

      /**
       * <pre>
       *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
       * </pre>
       *
       * <code>uint32 total_sequential_transactions_allowed = 6;</code>
       * @return The totalSequentialTransactionsAllowed.
       */
      @java.lang.Override
      public int getTotalSequentialTransactionsAllowed() {
        return instance.getTotalSequentialTransactionsAllowed();
      }
      /**
       * <pre>
       *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
       * </pre>
       *
       * <code>uint32 total_sequential_transactions_allowed = 6;</code>
       * @param value The totalSequentialTransactionsAllowed to set.
       * @return This builder for chaining.
       */
      public Builder setTotalSequentialTransactionsAllowed(int value) {
        copyOnWrite();
        instance.setTotalSequentialTransactionsAllowed(value);
        return this;
      }
      /**
       * <pre>
       *Quantidade de transações sequenciais (com o mesmo hash do PAN e PAN Sequence Number ou mesmo PAR) permitidas
       * </pre>
       *
       * <code>uint32 total_sequential_transactions_allowed = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalSequentialTransactionsAllowed() {
        copyOnWrite();
        instance.clearTotalSequentialTransactionsAllowed();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.AcceptedBankIdentificationNumber)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "messageId_",
              "index_",
              "issuerCode_",
              "initialRange_",
              "finalRange_",
              "totalSequentialTransactionsAllowed_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0004\u0004\u0003\u0005\u0003\u0006\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.AcceptedBankIdentificationNumber)
    private static final com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber DEFAULT_INSTANCE;
    static {
      AcceptedBankIdentificationNumber defaultInstance = new AcceptedBankIdentificationNumber();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AcceptedBankIdentificationNumber.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.AcceptedBin.AcceptedBankIdentificationNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AcceptedBankIdentificationNumber> PARSER;

    public static com.google.protobuf.Parser<AcceptedBankIdentificationNumber> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
