// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protos/application_identifier.proto

package com.axismobfintech.gpb.transactions;

public final class ApplicationIdentifierOuterClass {
  private ApplicationIdentifierOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code axis.transactions.FlagType}
   */
  public enum FlagType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <code>MASTERCARD_PAYPASS = 2;</code>
     */
    MASTERCARD_PAYPASS(2),
    /**
     * <code>VISA_PAYWAVE = 3;</code>
     */
    VISA_PAYWAVE(3),
    /**
     * <code>AMEX = 4;</code>
     */
    AMEX(4),
    /**
     * <code>JCB_QUICKPAY = 5;</code>
     */
    JCB_QUICKPAY(5),
    /**
     * <code>DISCOVER = 6;</code>
     */
    DISCOVER(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <code>MASTERCARD_PAYPASS = 2;</code>
     */
    public static final int MASTERCARD_PAYPASS_VALUE = 2;
    /**
     * <code>VISA_PAYWAVE = 3;</code>
     */
    public static final int VISA_PAYWAVE_VALUE = 3;
    /**
     * <code>AMEX = 4;</code>
     */
    public static final int AMEX_VALUE = 4;
    /**
     * <code>JCB_QUICKPAY = 5;</code>
     */
    public static final int JCB_QUICKPAY_VALUE = 5;
    /**
     * <code>DISCOVER = 6;</code>
     */
    public static final int DISCOVER_VALUE = 6;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FlagType valueOf(int value) {
      return forNumber(value);
    }

    public static FlagType forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 2: return MASTERCARD_PAYPASS;
        case 3: return VISA_PAYWAVE;
        case 4: return AMEX;
        case 5: return JCB_QUICKPAY;
        case 6: return DISCOVER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FlagType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FlagType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FlagType>() {
            @java.lang.Override
            public FlagType findValueByNumber(int number) {
              return FlagType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return FlagTypeVerifier.INSTANCE;
    }

    private static final class FlagTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new FlagTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return FlagType.forNumber(number) != null;
            }
          };

    private final int value;

    private FlagType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:axis.transactions.FlagType)
  }

  public interface ApplicationIdentifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.ApplicationIdentifier)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *AID - Application Identifier
     * </pre>
     *
     * <code>bytes application_identifier = 1;</code>
     * @return The applicationIdentifier.
     */
    com.google.protobuf.ByteString getApplicationIdentifier();

    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     * @return Whether the generalFlags field is set.
     */
    boolean hasGeneralFlags();
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     * @return The generalFlags.
     */
    com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags getGeneralFlags();

    /**
     * <pre>
     *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
     * </pre>
     *
     * <code>uint64 authorized_amount = 3;</code>
     * @return The authorizedAmount.
     */
    long getAuthorizedAmount();

    /**
     * <pre>
     *Código do país (Terminal Country Code)
     * </pre>
     *
     * <code>uint32 country_code = 4;</code>
     * @return The countryCode.
     */
    int getCountryCode();

    /**
     * <pre>
     *Código da moeda (Transaction Currency Code)
     * </pre>
     *
     * <code>uint32 currency_code = 5;</code>
     * @return The currencyCode.
     */
    int getCurrencyCode();

    /**
     * <pre>
     *Número de casas decimais do valor (Transaction Currency Exponent)
     * </pre>
     *
     * <code>uint32 currency_exponent = 6;</code>
     * @return The currencyExponent.
     */
    int getCurrencyExponent();

    /**
     * <pre>
     *Tipo de terminal (Terminal Type)
     * </pre>
     *
     * <code>uint32 terminal_type = 7;</code>
     * @return The terminalType.
     */
    int getTerminalType();

    /**
     * <pre>
     *MCC - Merchant Category Code 
     * </pre>
     *
     * <code>uint32 merchant_category_code = 8;</code>
     * @return The merchantCategoryCode.
     */
    int getMerchantCategoryCode();

    /**
     * <pre>
     *TTQ (Terminal Transaction Qualifiers)
     * </pre>
     *
     * <code>bytes terminal_transaction_qualifiers = 9;</code>
     * @return The terminalTransactionQualifiers.
     */
    com.google.protobuf.ByteString getTerminalTransactionQualifiers();

    /**
     * <pre>
     *Reader/Terminal Contactless Floor Limit
     * </pre>
     *
     * <code>uint64 contactless_floor_limit = 10;</code>
     * @return The contactlessFloorLimit.
     */
    long getContactlessFloorLimit();

    /**
     * <pre>
     *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
     * </pre>
     *
     * <code>bytes reader_floor_limit = 11;</code>
     * @return The readerFloorLimit.
     */
    com.google.protobuf.ByteString getReaderFloorLimit();

    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_no_on_device = 12;</code>
     * @return The limitNoOnDevice.
     */
    long getLimitNoOnDevice();

    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_on_device = 13;</code>
     * @return The limitOnDevice.
     */
    long getLimitOnDevice();

    /**
     * <pre>
     *Reader/Terminal CVM Required Limit
     * </pre>
     *
     * <code>uint64 cvm_required_limit = 14;</code>
     * @return The cvmRequiredLimit.
     */
    long getCvmRequiredLimit();

    /**
     * <pre>
     *Terminal Capabilities 
     * </pre>
     *
     * <code>bytes terminal_capabilities = 15;</code>
     * @return The terminalCapabilities.
     */
    com.google.protobuf.ByteString getTerminalCapabilities();

    /**
     * <pre>
     *Additional Terminal Capabilities
     * </pre>
     *
     * <code>bytes addictional_terminal_capabilities = 16;</code>
     * @return The addictionalTerminalCapabilities.
     */
    com.google.protobuf.ByteString getAddictionalTerminalCapabilities();

    /**
     * <pre>
     *Application Version Number - EMV
     * </pre>
     *
     * <code>bytes application_version_number = 17;</code>
     * @return The applicationVersionNumber.
     */
    com.google.protobuf.ByteString getApplicationVersionNumber();

    /**
     * <pre>
     *Card Data Input Capability
     * </pre>
     *
     * <code>bytes card_data_input_capability = 18;</code>
     * @return The cardDataInputCapability.
     */
    com.google.protobuf.ByteString getCardDataInputCapability();

    /**
     * <pre>
     *CVM Capability - CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_required = 19;</code>
     * @return The cvmCapabilityRequired.
     */
    com.google.protobuf.ByteString getCvmCapabilityRequired();

    /**
     * <pre>
     *CVM Capability - No CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_not_required = 20;</code>
     * @return The cvmCapabilityNotRequired.
     */
    com.google.protobuf.ByteString getCvmCapabilityNotRequired();

    /**
     * <pre>
     *Security Capability 
     * </pre>
     *
     * <code>bytes security_capability = 21;</code>
     * @return The securityCapability.
     */
    com.google.protobuf.ByteString getSecurityCapability();

    /**
     * <pre>
     *Terminal Action Code - Default
     * </pre>
     *
     * <code>bytes terminal_action_code_default = 22;</code>
     * @return The terminalActionCodeDefault.
     */
    com.google.protobuf.ByteString getTerminalActionCodeDefault();

    /**
     * <pre>
     *Terminal Action Code - Denial
     * </pre>
     *
     * <code>bytes terminal_action_code_denial = 23;</code>
     * @return The terminalActionCodeDenial.
     */
    com.google.protobuf.ByteString getTerminalActionCodeDenial();

    /**
     * <pre>
     *Terminal Action Code - Online
     * </pre>
     *
     * <code>bytes terminal_action_code_online = 24;</code>
     * @return The terminalActionCodeOnline.
     */
    com.google.protobuf.ByteString getTerminalActionCodeOnline();

    /**
     * <pre>
     *Terminal Risk Management Data
     * </pre>
     *
     * <code>bytes risk_management_data = 25;</code>
     * @return The riskManagementData.
     */
    com.google.protobuf.ByteString getRiskManagementData();

    /**
     * <pre>
     *Transaction Category Code 
     * </pre>
     *
     * <code>bytes category_code = 26;</code>
     * @return The categoryCode.
     */
    com.google.protobuf.ByteString getCategoryCode();
  }
  /**
   * Protobuf type {@code axis.transactions.ApplicationIdentifier}
   */
  public  static final class ApplicationIdentifier extends
      com.google.protobuf.GeneratedMessageLite<
          ApplicationIdentifier, ApplicationIdentifier.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.ApplicationIdentifier)
      ApplicationIdentifierOrBuilder {
    private ApplicationIdentifier() {
      applicationIdentifier_ = com.google.protobuf.ByteString.EMPTY;
      terminalTransactionQualifiers_ = com.google.protobuf.ByteString.EMPTY;
      readerFloorLimit_ = com.google.protobuf.ByteString.EMPTY;
      terminalCapabilities_ = com.google.protobuf.ByteString.EMPTY;
      addictionalTerminalCapabilities_ = com.google.protobuf.ByteString.EMPTY;
      applicationVersionNumber_ = com.google.protobuf.ByteString.EMPTY;
      cardDataInputCapability_ = com.google.protobuf.ByteString.EMPTY;
      cvmCapabilityRequired_ = com.google.protobuf.ByteString.EMPTY;
      cvmCapabilityNotRequired_ = com.google.protobuf.ByteString.EMPTY;
      securityCapability_ = com.google.protobuf.ByteString.EMPTY;
      terminalActionCodeDefault_ = com.google.protobuf.ByteString.EMPTY;
      terminalActionCodeDenial_ = com.google.protobuf.ByteString.EMPTY;
      terminalActionCodeOnline_ = com.google.protobuf.ByteString.EMPTY;
      riskManagementData_ = com.google.protobuf.ByteString.EMPTY;
      categoryCode_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int APPLICATION_IDENTIFIER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString applicationIdentifier_;
    /**
     * <pre>
     *AID - Application Identifier
     * </pre>
     *
     * <code>bytes application_identifier = 1;</code>
     * @return The applicationIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getApplicationIdentifier() {
      return applicationIdentifier_;
    }
    /**
     * <pre>
     *AID - Application Identifier
     * </pre>
     *
     * <code>bytes application_identifier = 1;</code>
     * @param value The applicationIdentifier to set.
     */
    private void setApplicationIdentifier(com.google.protobuf.ByteString value) {
      value.getClass();
  
      applicationIdentifier_ = value;
    }
    /**
     * <pre>
     *AID - Application Identifier
     * </pre>
     *
     * <code>bytes application_identifier = 1;</code>
     */
    private void clearApplicationIdentifier() {
      
      applicationIdentifier_ = getDefaultInstance().getApplicationIdentifier();
    }

    public static final int GENERAL_FLAGS_FIELD_NUMBER = 2;
    private com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags generalFlags_;
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     */
    @java.lang.Override
    public boolean hasGeneralFlags() {
      return generalFlags_ != null;
    }
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags getGeneralFlags() {
      return generalFlags_ == null ? com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.getDefaultInstance() : generalFlags_;
    }
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     */
    private void setGeneralFlags(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags value) {
      value.getClass();
  generalFlags_ = value;
      
      }
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeGeneralFlags(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags value) {
      value.getClass();
  if (generalFlags_ != null &&
          generalFlags_ != com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.getDefaultInstance()) {
        generalFlags_ =
          com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.newBuilder(generalFlags_).mergeFrom(value).buildPartial();
      } else {
        generalFlags_ = value;
      }
      
    }
    /**
     * <pre>
     *Flags gerais (8 bits - ver tabela a seguir).
     * </pre>
     *
     * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
     */
    private void clearGeneralFlags() {  generalFlags_ = null;
      
    }

    public static final int AUTHORIZED_AMOUNT_FIELD_NUMBER = 3;
    private long authorizedAmount_;
    /**
     * <pre>
     *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
     * </pre>
     *
     * <code>uint64 authorized_amount = 3;</code>
     * @return The authorizedAmount.
     */
    @java.lang.Override
    public long getAuthorizedAmount() {
      return authorizedAmount_;
    }
    /**
     * <pre>
     *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
     * </pre>
     *
     * <code>uint64 authorized_amount = 3;</code>
     * @param value The authorizedAmount to set.
     */
    private void setAuthorizedAmount(long value) {
      
      authorizedAmount_ = value;
    }
    /**
     * <pre>
     *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
     * </pre>
     *
     * <code>uint64 authorized_amount = 3;</code>
     */
    private void clearAuthorizedAmount() {
      
      authorizedAmount_ = 0L;
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 4;
    private int countryCode_;
    /**
     * <pre>
     *Código do país (Terminal Country Code)
     * </pre>
     *
     * <code>uint32 country_code = 4;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public int getCountryCode() {
      return countryCode_;
    }
    /**
     * <pre>
     *Código do país (Terminal Country Code)
     * </pre>
     *
     * <code>uint32 country_code = 4;</code>
     * @param value The countryCode to set.
     */
    private void setCountryCode(int value) {
      
      countryCode_ = value;
    }
    /**
     * <pre>
     *Código do país (Terminal Country Code)
     * </pre>
     *
     * <code>uint32 country_code = 4;</code>
     */
    private void clearCountryCode() {
      
      countryCode_ = 0;
    }

    public static final int CURRENCY_CODE_FIELD_NUMBER = 5;
    private int currencyCode_;
    /**
     * <pre>
     *Código da moeda (Transaction Currency Code)
     * </pre>
     *
     * <code>uint32 currency_code = 5;</code>
     * @return The currencyCode.
     */
    @java.lang.Override
    public int getCurrencyCode() {
      return currencyCode_;
    }
    /**
     * <pre>
     *Código da moeda (Transaction Currency Code)
     * </pre>
     *
     * <code>uint32 currency_code = 5;</code>
     * @param value The currencyCode to set.
     */
    private void setCurrencyCode(int value) {
      
      currencyCode_ = value;
    }
    /**
     * <pre>
     *Código da moeda (Transaction Currency Code)
     * </pre>
     *
     * <code>uint32 currency_code = 5;</code>
     */
    private void clearCurrencyCode() {
      
      currencyCode_ = 0;
    }

    public static final int CURRENCY_EXPONENT_FIELD_NUMBER = 6;
    private int currencyExponent_;
    /**
     * <pre>
     *Número de casas decimais do valor (Transaction Currency Exponent)
     * </pre>
     *
     * <code>uint32 currency_exponent = 6;</code>
     * @return The currencyExponent.
     */
    @java.lang.Override
    public int getCurrencyExponent() {
      return currencyExponent_;
    }
    /**
     * <pre>
     *Número de casas decimais do valor (Transaction Currency Exponent)
     * </pre>
     *
     * <code>uint32 currency_exponent = 6;</code>
     * @param value The currencyExponent to set.
     */
    private void setCurrencyExponent(int value) {
      
      currencyExponent_ = value;
    }
    /**
     * <pre>
     *Número de casas decimais do valor (Transaction Currency Exponent)
     * </pre>
     *
     * <code>uint32 currency_exponent = 6;</code>
     */
    private void clearCurrencyExponent() {
      
      currencyExponent_ = 0;
    }

    public static final int TERMINAL_TYPE_FIELD_NUMBER = 7;
    private int terminalType_;
    /**
     * <pre>
     *Tipo de terminal (Terminal Type)
     * </pre>
     *
     * <code>uint32 terminal_type = 7;</code>
     * @return The terminalType.
     */
    @java.lang.Override
    public int getTerminalType() {
      return terminalType_;
    }
    /**
     * <pre>
     *Tipo de terminal (Terminal Type)
     * </pre>
     *
     * <code>uint32 terminal_type = 7;</code>
     * @param value The terminalType to set.
     */
    private void setTerminalType(int value) {
      
      terminalType_ = value;
    }
    /**
     * <pre>
     *Tipo de terminal (Terminal Type)
     * </pre>
     *
     * <code>uint32 terminal_type = 7;</code>
     */
    private void clearTerminalType() {
      
      terminalType_ = 0;
    }

    public static final int MERCHANT_CATEGORY_CODE_FIELD_NUMBER = 8;
    private int merchantCategoryCode_;
    /**
     * <pre>
     *MCC - Merchant Category Code 
     * </pre>
     *
     * <code>uint32 merchant_category_code = 8;</code>
     * @return The merchantCategoryCode.
     */
    @java.lang.Override
    public int getMerchantCategoryCode() {
      return merchantCategoryCode_;
    }
    /**
     * <pre>
     *MCC - Merchant Category Code 
     * </pre>
     *
     * <code>uint32 merchant_category_code = 8;</code>
     * @param value The merchantCategoryCode to set.
     */
    private void setMerchantCategoryCode(int value) {
      
      merchantCategoryCode_ = value;
    }
    /**
     * <pre>
     *MCC - Merchant Category Code 
     * </pre>
     *
     * <code>uint32 merchant_category_code = 8;</code>
     */
    private void clearMerchantCategoryCode() {
      
      merchantCategoryCode_ = 0;
    }

    public static final int TERMINAL_TRANSACTION_QUALIFIERS_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString terminalTransactionQualifiers_;
    /**
     * <pre>
     *TTQ (Terminal Transaction Qualifiers)
     * </pre>
     *
     * <code>bytes terminal_transaction_qualifiers = 9;</code>
     * @return The terminalTransactionQualifiers.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerminalTransactionQualifiers() {
      return terminalTransactionQualifiers_;
    }
    /**
     * <pre>
     *TTQ (Terminal Transaction Qualifiers)
     * </pre>
     *
     * <code>bytes terminal_transaction_qualifiers = 9;</code>
     * @param value The terminalTransactionQualifiers to set.
     */
    private void setTerminalTransactionQualifiers(com.google.protobuf.ByteString value) {
      value.getClass();
  
      terminalTransactionQualifiers_ = value;
    }
    /**
     * <pre>
     *TTQ (Terminal Transaction Qualifiers)
     * </pre>
     *
     * <code>bytes terminal_transaction_qualifiers = 9;</code>
     */
    private void clearTerminalTransactionQualifiers() {
      
      terminalTransactionQualifiers_ = getDefaultInstance().getTerminalTransactionQualifiers();
    }

    public static final int CONTACTLESS_FLOOR_LIMIT_FIELD_NUMBER = 10;
    private long contactlessFloorLimit_;
    /**
     * <pre>
     *Reader/Terminal Contactless Floor Limit
     * </pre>
     *
     * <code>uint64 contactless_floor_limit = 10;</code>
     * @return The contactlessFloorLimit.
     */
    @java.lang.Override
    public long getContactlessFloorLimit() {
      return contactlessFloorLimit_;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Floor Limit
     * </pre>
     *
     * <code>uint64 contactless_floor_limit = 10;</code>
     * @param value The contactlessFloorLimit to set.
     */
    private void setContactlessFloorLimit(long value) {
      
      contactlessFloorLimit_ = value;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Floor Limit
     * </pre>
     *
     * <code>uint64 contactless_floor_limit = 10;</code>
     */
    private void clearContactlessFloorLimit() {
      
      contactlessFloorLimit_ = 0L;
    }

    public static final int READER_FLOOR_LIMIT_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString readerFloorLimit_;
    /**
     * <pre>
     *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
     * </pre>
     *
     * <code>bytes reader_floor_limit = 11;</code>
     * @return The readerFloorLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getReaderFloorLimit() {
      return readerFloorLimit_;
    }
    /**
     * <pre>
     *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
     * </pre>
     *
     * <code>bytes reader_floor_limit = 11;</code>
     * @param value The readerFloorLimit to set.
     */
    private void setReaderFloorLimit(com.google.protobuf.ByteString value) {
      value.getClass();
  
      readerFloorLimit_ = value;
    }
    /**
     * <pre>
     *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
     * </pre>
     *
     * <code>bytes reader_floor_limit = 11;</code>
     */
    private void clearReaderFloorLimit() {
      
      readerFloorLimit_ = getDefaultInstance().getReaderFloorLimit();
    }

    public static final int LIMIT_NO_ON_DEVICE_FIELD_NUMBER = 12;
    private long limitNoOnDevice_;
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_no_on_device = 12;</code>
     * @return The limitNoOnDevice.
     */
    @java.lang.Override
    public long getLimitNoOnDevice() {
      return limitNoOnDevice_;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_no_on_device = 12;</code>
     * @param value The limitNoOnDevice to set.
     */
    private void setLimitNoOnDevice(long value) {
      
      limitNoOnDevice_ = value;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_no_on_device = 12;</code>
     */
    private void clearLimitNoOnDevice() {
      
      limitNoOnDevice_ = 0L;
    }

    public static final int LIMIT_ON_DEVICE_FIELD_NUMBER = 13;
    private long limitOnDevice_;
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_on_device = 13;</code>
     * @return The limitOnDevice.
     */
    @java.lang.Override
    public long getLimitOnDevice() {
      return limitOnDevice_;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_on_device = 13;</code>
     * @param value The limitOnDevice to set.
     */
    private void setLimitOnDevice(long value) {
      
      limitOnDevice_ = value;
    }
    /**
     * <pre>
     *Reader/Terminal Contactless Transaction Limit (On-device CVM)
     * </pre>
     *
     * <code>uint64 limit_on_device = 13;</code>
     */
    private void clearLimitOnDevice() {
      
      limitOnDevice_ = 0L;
    }

    public static final int CVM_REQUIRED_LIMIT_FIELD_NUMBER = 14;
    private long cvmRequiredLimit_;
    /**
     * <pre>
     *Reader/Terminal CVM Required Limit
     * </pre>
     *
     * <code>uint64 cvm_required_limit = 14;</code>
     * @return The cvmRequiredLimit.
     */
    @java.lang.Override
    public long getCvmRequiredLimit() {
      return cvmRequiredLimit_;
    }
    /**
     * <pre>
     *Reader/Terminal CVM Required Limit
     * </pre>
     *
     * <code>uint64 cvm_required_limit = 14;</code>
     * @param value The cvmRequiredLimit to set.
     */
    private void setCvmRequiredLimit(long value) {
      
      cvmRequiredLimit_ = value;
    }
    /**
     * <pre>
     *Reader/Terminal CVM Required Limit
     * </pre>
     *
     * <code>uint64 cvm_required_limit = 14;</code>
     */
    private void clearCvmRequiredLimit() {
      
      cvmRequiredLimit_ = 0L;
    }

    public static final int TERMINAL_CAPABILITIES_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString terminalCapabilities_;
    /**
     * <pre>
     *Terminal Capabilities 
     * </pre>
     *
     * <code>bytes terminal_capabilities = 15;</code>
     * @return The terminalCapabilities.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerminalCapabilities() {
      return terminalCapabilities_;
    }
    /**
     * <pre>
     *Terminal Capabilities 
     * </pre>
     *
     * <code>bytes terminal_capabilities = 15;</code>
     * @param value The terminalCapabilities to set.
     */
    private void setTerminalCapabilities(com.google.protobuf.ByteString value) {
      value.getClass();
  
      terminalCapabilities_ = value;
    }
    /**
     * <pre>
     *Terminal Capabilities 
     * </pre>
     *
     * <code>bytes terminal_capabilities = 15;</code>
     */
    private void clearTerminalCapabilities() {
      
      terminalCapabilities_ = getDefaultInstance().getTerminalCapabilities();
    }

    public static final int ADDICTIONAL_TERMINAL_CAPABILITIES_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString addictionalTerminalCapabilities_;
    /**
     * <pre>
     *Additional Terminal Capabilities
     * </pre>
     *
     * <code>bytes addictional_terminal_capabilities = 16;</code>
     * @return The addictionalTerminalCapabilities.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAddictionalTerminalCapabilities() {
      return addictionalTerminalCapabilities_;
    }
    /**
     * <pre>
     *Additional Terminal Capabilities
     * </pre>
     *
     * <code>bytes addictional_terminal_capabilities = 16;</code>
     * @param value The addictionalTerminalCapabilities to set.
     */
    private void setAddictionalTerminalCapabilities(com.google.protobuf.ByteString value) {
      value.getClass();
  
      addictionalTerminalCapabilities_ = value;
    }
    /**
     * <pre>
     *Additional Terminal Capabilities
     * </pre>
     *
     * <code>bytes addictional_terminal_capabilities = 16;</code>
     */
    private void clearAddictionalTerminalCapabilities() {
      
      addictionalTerminalCapabilities_ = getDefaultInstance().getAddictionalTerminalCapabilities();
    }

    public static final int APPLICATION_VERSION_NUMBER_FIELD_NUMBER = 17;
    private com.google.protobuf.ByteString applicationVersionNumber_;
    /**
     * <pre>
     *Application Version Number - EMV
     * </pre>
     *
     * <code>bytes application_version_number = 17;</code>
     * @return The applicationVersionNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getApplicationVersionNumber() {
      return applicationVersionNumber_;
    }
    /**
     * <pre>
     *Application Version Number - EMV
     * </pre>
     *
     * <code>bytes application_version_number = 17;</code>
     * @param value The applicationVersionNumber to set.
     */
    private void setApplicationVersionNumber(com.google.protobuf.ByteString value) {
      value.getClass();
  
      applicationVersionNumber_ = value;
    }
    /**
     * <pre>
     *Application Version Number - EMV
     * </pre>
     *
     * <code>bytes application_version_number = 17;</code>
     */
    private void clearApplicationVersionNumber() {
      
      applicationVersionNumber_ = getDefaultInstance().getApplicationVersionNumber();
    }

    public static final int CARD_DATA_INPUT_CAPABILITY_FIELD_NUMBER = 18;
    private com.google.protobuf.ByteString cardDataInputCapability_;
    /**
     * <pre>
     *Card Data Input Capability
     * </pre>
     *
     * <code>bytes card_data_input_capability = 18;</code>
     * @return The cardDataInputCapability.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCardDataInputCapability() {
      return cardDataInputCapability_;
    }
    /**
     * <pre>
     *Card Data Input Capability
     * </pre>
     *
     * <code>bytes card_data_input_capability = 18;</code>
     * @param value The cardDataInputCapability to set.
     */
    private void setCardDataInputCapability(com.google.protobuf.ByteString value) {
      value.getClass();
  
      cardDataInputCapability_ = value;
    }
    /**
     * <pre>
     *Card Data Input Capability
     * </pre>
     *
     * <code>bytes card_data_input_capability = 18;</code>
     */
    private void clearCardDataInputCapability() {
      
      cardDataInputCapability_ = getDefaultInstance().getCardDataInputCapability();
    }

    public static final int CVM_CAPABILITY_REQUIRED_FIELD_NUMBER = 19;
    private com.google.protobuf.ByteString cvmCapabilityRequired_;
    /**
     * <pre>
     *CVM Capability - CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_required = 19;</code>
     * @return The cvmCapabilityRequired.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCvmCapabilityRequired() {
      return cvmCapabilityRequired_;
    }
    /**
     * <pre>
     *CVM Capability - CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_required = 19;</code>
     * @param value The cvmCapabilityRequired to set.
     */
    private void setCvmCapabilityRequired(com.google.protobuf.ByteString value) {
      value.getClass();
  
      cvmCapabilityRequired_ = value;
    }
    /**
     * <pre>
     *CVM Capability - CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_required = 19;</code>
     */
    private void clearCvmCapabilityRequired() {
      
      cvmCapabilityRequired_ = getDefaultInstance().getCvmCapabilityRequired();
    }

    public static final int CVM_CAPABILITY_NOT_REQUIRED_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString cvmCapabilityNotRequired_;
    /**
     * <pre>
     *CVM Capability - No CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_not_required = 20;</code>
     * @return The cvmCapabilityNotRequired.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCvmCapabilityNotRequired() {
      return cvmCapabilityNotRequired_;
    }
    /**
     * <pre>
     *CVM Capability - No CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_not_required = 20;</code>
     * @param value The cvmCapabilityNotRequired to set.
     */
    private void setCvmCapabilityNotRequired(com.google.protobuf.ByteString value) {
      value.getClass();
  
      cvmCapabilityNotRequired_ = value;
    }
    /**
     * <pre>
     *CVM Capability - No CVM Required
     * </pre>
     *
     * <code>bytes cvm_capability_not_required = 20;</code>
     */
    private void clearCvmCapabilityNotRequired() {
      
      cvmCapabilityNotRequired_ = getDefaultInstance().getCvmCapabilityNotRequired();
    }

    public static final int SECURITY_CAPABILITY_FIELD_NUMBER = 21;
    private com.google.protobuf.ByteString securityCapability_;
    /**
     * <pre>
     *Security Capability 
     * </pre>
     *
     * <code>bytes security_capability = 21;</code>
     * @return The securityCapability.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSecurityCapability() {
      return securityCapability_;
    }
    /**
     * <pre>
     *Security Capability 
     * </pre>
     *
     * <code>bytes security_capability = 21;</code>
     * @param value The securityCapability to set.
     */
    private void setSecurityCapability(com.google.protobuf.ByteString value) {
      value.getClass();
  
      securityCapability_ = value;
    }
    /**
     * <pre>
     *Security Capability 
     * </pre>
     *
     * <code>bytes security_capability = 21;</code>
     */
    private void clearSecurityCapability() {
      
      securityCapability_ = getDefaultInstance().getSecurityCapability();
    }

    public static final int TERMINAL_ACTION_CODE_DEFAULT_FIELD_NUMBER = 22;
    private com.google.protobuf.ByteString terminalActionCodeDefault_;
    /**
     * <pre>
     *Terminal Action Code - Default
     * </pre>
     *
     * <code>bytes terminal_action_code_default = 22;</code>
     * @return The terminalActionCodeDefault.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerminalActionCodeDefault() {
      return terminalActionCodeDefault_;
    }
    /**
     * <pre>
     *Terminal Action Code - Default
     * </pre>
     *
     * <code>bytes terminal_action_code_default = 22;</code>
     * @param value The terminalActionCodeDefault to set.
     */
    private void setTerminalActionCodeDefault(com.google.protobuf.ByteString value) {
      value.getClass();
  
      terminalActionCodeDefault_ = value;
    }
    /**
     * <pre>
     *Terminal Action Code - Default
     * </pre>
     *
     * <code>bytes terminal_action_code_default = 22;</code>
     */
    private void clearTerminalActionCodeDefault() {
      
      terminalActionCodeDefault_ = getDefaultInstance().getTerminalActionCodeDefault();
    }

    public static final int TERMINAL_ACTION_CODE_DENIAL_FIELD_NUMBER = 23;
    private com.google.protobuf.ByteString terminalActionCodeDenial_;
    /**
     * <pre>
     *Terminal Action Code - Denial
     * </pre>
     *
     * <code>bytes terminal_action_code_denial = 23;</code>
     * @return The terminalActionCodeDenial.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerminalActionCodeDenial() {
      return terminalActionCodeDenial_;
    }
    /**
     * <pre>
     *Terminal Action Code - Denial
     * </pre>
     *
     * <code>bytes terminal_action_code_denial = 23;</code>
     * @param value The terminalActionCodeDenial to set.
     */
    private void setTerminalActionCodeDenial(com.google.protobuf.ByteString value) {
      value.getClass();
  
      terminalActionCodeDenial_ = value;
    }
    /**
     * <pre>
     *Terminal Action Code - Denial
     * </pre>
     *
     * <code>bytes terminal_action_code_denial = 23;</code>
     */
    private void clearTerminalActionCodeDenial() {
      
      terminalActionCodeDenial_ = getDefaultInstance().getTerminalActionCodeDenial();
    }

    public static final int TERMINAL_ACTION_CODE_ONLINE_FIELD_NUMBER = 24;
    private com.google.protobuf.ByteString terminalActionCodeOnline_;
    /**
     * <pre>
     *Terminal Action Code - Online
     * </pre>
     *
     * <code>bytes terminal_action_code_online = 24;</code>
     * @return The terminalActionCodeOnline.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerminalActionCodeOnline() {
      return terminalActionCodeOnline_;
    }
    /**
     * <pre>
     *Terminal Action Code - Online
     * </pre>
     *
     * <code>bytes terminal_action_code_online = 24;</code>
     * @param value The terminalActionCodeOnline to set.
     */
    private void setTerminalActionCodeOnline(com.google.protobuf.ByteString value) {
      value.getClass();
  
      terminalActionCodeOnline_ = value;
    }
    /**
     * <pre>
     *Terminal Action Code - Online
     * </pre>
     *
     * <code>bytes terminal_action_code_online = 24;</code>
     */
    private void clearTerminalActionCodeOnline() {
      
      terminalActionCodeOnline_ = getDefaultInstance().getTerminalActionCodeOnline();
    }

    public static final int RISK_MANAGEMENT_DATA_FIELD_NUMBER = 25;
    private com.google.protobuf.ByteString riskManagementData_;
    /**
     * <pre>
     *Terminal Risk Management Data
     * </pre>
     *
     * <code>bytes risk_management_data = 25;</code>
     * @return The riskManagementData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRiskManagementData() {
      return riskManagementData_;
    }
    /**
     * <pre>
     *Terminal Risk Management Data
     * </pre>
     *
     * <code>bytes risk_management_data = 25;</code>
     * @param value The riskManagementData to set.
     */
    private void setRiskManagementData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      riskManagementData_ = value;
    }
    /**
     * <pre>
     *Terminal Risk Management Data
     * </pre>
     *
     * <code>bytes risk_management_data = 25;</code>
     */
    private void clearRiskManagementData() {
      
      riskManagementData_ = getDefaultInstance().getRiskManagementData();
    }

    public static final int CATEGORY_CODE_FIELD_NUMBER = 26;
    private com.google.protobuf.ByteString categoryCode_;
    /**
     * <pre>
     *Transaction Category Code 
     * </pre>
     *
     * <code>bytes category_code = 26;</code>
     * @return The categoryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCategoryCode() {
      return categoryCode_;
    }
    /**
     * <pre>
     *Transaction Category Code 
     * </pre>
     *
     * <code>bytes category_code = 26;</code>
     * @param value The categoryCode to set.
     */
    private void setCategoryCode(com.google.protobuf.ByteString value) {
      value.getClass();
  
      categoryCode_ = value;
    }
    /**
     * <pre>
     *Transaction Category Code 
     * </pre>
     *
     * <code>bytes category_code = 26;</code>
     */
    private void clearCategoryCode() {
      
      categoryCode_ = getDefaultInstance().getCategoryCode();
    }

    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.ApplicationIdentifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.ApplicationIdentifier)
        com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifierOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *AID - Application Identifier
       * </pre>
       *
       * <code>bytes application_identifier = 1;</code>
       * @return The applicationIdentifier.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getApplicationIdentifier() {
        return instance.getApplicationIdentifier();
      }
      /**
       * <pre>
       *AID - Application Identifier
       * </pre>
       *
       * <code>bytes application_identifier = 1;</code>
       * @param value The applicationIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationIdentifier(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setApplicationIdentifier(value);
        return this;
      }
      /**
       * <pre>
       *AID - Application Identifier
       * </pre>
       *
       * <code>bytes application_identifier = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationIdentifier() {
        copyOnWrite();
        instance.clearApplicationIdentifier();
        return this;
      }

      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      @java.lang.Override
      public boolean hasGeneralFlags() {
        return instance.hasGeneralFlags();
      }
      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags getGeneralFlags() {
        return instance.getGeneralFlags();
      }
      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      public Builder setGeneralFlags(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags value) {
        copyOnWrite();
        instance.setGeneralFlags(value);
        return this;
        }
      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      public Builder setGeneralFlags(
          com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.Builder builderForValue) {
        copyOnWrite();
        instance.setGeneralFlags(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      public Builder mergeGeneralFlags(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags value) {
        copyOnWrite();
        instance.mergeGeneralFlags(value);
        return this;
      }
      /**
       * <pre>
       *Flags gerais (8 bits - ver tabela a seguir).
       * </pre>
       *
       * <code>.axis.transactions.GeneralFlags general_flags = 2;</code>
       */
      public Builder clearGeneralFlags() {  copyOnWrite();
        instance.clearGeneralFlags();
        return this;
      }

      /**
       * <pre>
       *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
       * </pre>
       *
       * <code>uint64 authorized_amount = 3;</code>
       * @return The authorizedAmount.
       */
      @java.lang.Override
      public long getAuthorizedAmount() {
        return instance.getAuthorizedAmount();
      }
      /**
       * <pre>
       *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
       * </pre>
       *
       * <code>uint64 authorized_amount = 3;</code>
       * @param value The authorizedAmount to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizedAmount(long value) {
        copyOnWrite();
        instance.setAuthorizedAmount(value);
        return this;
      }
      /**
       * <pre>
       *Valor padrão a ser usado para a transação (Amount, Authorized - Numeric)
       * </pre>
       *
       * <code>uint64 authorized_amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizedAmount() {
        copyOnWrite();
        instance.clearAuthorizedAmount();
        return this;
      }

      /**
       * <pre>
       *Código do país (Terminal Country Code)
       * </pre>
       *
       * <code>uint32 country_code = 4;</code>
       * @return The countryCode.
       */
      @java.lang.Override
      public int getCountryCode() {
        return instance.getCountryCode();
      }
      /**
       * <pre>
       *Código do país (Terminal Country Code)
       * </pre>
       *
       * <code>uint32 country_code = 4;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(int value) {
        copyOnWrite();
        instance.setCountryCode(value);
        return this;
      }
      /**
       * <pre>
       *Código do país (Terminal Country Code)
       * </pre>
       *
       * <code>uint32 country_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        copyOnWrite();
        instance.clearCountryCode();
        return this;
      }

      /**
       * <pre>
       *Código da moeda (Transaction Currency Code)
       * </pre>
       *
       * <code>uint32 currency_code = 5;</code>
       * @return The currencyCode.
       */
      @java.lang.Override
      public int getCurrencyCode() {
        return instance.getCurrencyCode();
      }
      /**
       * <pre>
       *Código da moeda (Transaction Currency Code)
       * </pre>
       *
       * <code>uint32 currency_code = 5;</code>
       * @param value The currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCode(int value) {
        copyOnWrite();
        instance.setCurrencyCode(value);
        return this;
      }
      /**
       * <pre>
       *Código da moeda (Transaction Currency Code)
       * </pre>
       *
       * <code>uint32 currency_code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyCode() {
        copyOnWrite();
        instance.clearCurrencyCode();
        return this;
      }

      /**
       * <pre>
       *Número de casas decimais do valor (Transaction Currency Exponent)
       * </pre>
       *
       * <code>uint32 currency_exponent = 6;</code>
       * @return The currencyExponent.
       */
      @java.lang.Override
      public int getCurrencyExponent() {
        return instance.getCurrencyExponent();
      }
      /**
       * <pre>
       *Número de casas decimais do valor (Transaction Currency Exponent)
       * </pre>
       *
       * <code>uint32 currency_exponent = 6;</code>
       * @param value The currencyExponent to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyExponent(int value) {
        copyOnWrite();
        instance.setCurrencyExponent(value);
        return this;
      }
      /**
       * <pre>
       *Número de casas decimais do valor (Transaction Currency Exponent)
       * </pre>
       *
       * <code>uint32 currency_exponent = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyExponent() {
        copyOnWrite();
        instance.clearCurrencyExponent();
        return this;
      }

      /**
       * <pre>
       *Tipo de terminal (Terminal Type)
       * </pre>
       *
       * <code>uint32 terminal_type = 7;</code>
       * @return The terminalType.
       */
      @java.lang.Override
      public int getTerminalType() {
        return instance.getTerminalType();
      }
      /**
       * <pre>
       *Tipo de terminal (Terminal Type)
       * </pre>
       *
       * <code>uint32 terminal_type = 7;</code>
       * @param value The terminalType to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalType(int value) {
        copyOnWrite();
        instance.setTerminalType(value);
        return this;
      }
      /**
       * <pre>
       *Tipo de terminal (Terminal Type)
       * </pre>
       *
       * <code>uint32 terminal_type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalType() {
        copyOnWrite();
        instance.clearTerminalType();
        return this;
      }

      /**
       * <pre>
       *MCC - Merchant Category Code 
       * </pre>
       *
       * <code>uint32 merchant_category_code = 8;</code>
       * @return The merchantCategoryCode.
       */
      @java.lang.Override
      public int getMerchantCategoryCode() {
        return instance.getMerchantCategoryCode();
      }
      /**
       * <pre>
       *MCC - Merchant Category Code 
       * </pre>
       *
       * <code>uint32 merchant_category_code = 8;</code>
       * @param value The merchantCategoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantCategoryCode(int value) {
        copyOnWrite();
        instance.setMerchantCategoryCode(value);
        return this;
      }
      /**
       * <pre>
       *MCC - Merchant Category Code 
       * </pre>
       *
       * <code>uint32 merchant_category_code = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantCategoryCode() {
        copyOnWrite();
        instance.clearMerchantCategoryCode();
        return this;
      }

      /**
       * <pre>
       *TTQ (Terminal Transaction Qualifiers)
       * </pre>
       *
       * <code>bytes terminal_transaction_qualifiers = 9;</code>
       * @return The terminalTransactionQualifiers.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerminalTransactionQualifiers() {
        return instance.getTerminalTransactionQualifiers();
      }
      /**
       * <pre>
       *TTQ (Terminal Transaction Qualifiers)
       * </pre>
       *
       * <code>bytes terminal_transaction_qualifiers = 9;</code>
       * @param value The terminalTransactionQualifiers to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalTransactionQualifiers(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTerminalTransactionQualifiers(value);
        return this;
      }
      /**
       * <pre>
       *TTQ (Terminal Transaction Qualifiers)
       * </pre>
       *
       * <code>bytes terminal_transaction_qualifiers = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalTransactionQualifiers() {
        copyOnWrite();
        instance.clearTerminalTransactionQualifiers();
        return this;
      }

      /**
       * <pre>
       *Reader/Terminal Contactless Floor Limit
       * </pre>
       *
       * <code>uint64 contactless_floor_limit = 10;</code>
       * @return The contactlessFloorLimit.
       */
      @java.lang.Override
      public long getContactlessFloorLimit() {
        return instance.getContactlessFloorLimit();
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Floor Limit
       * </pre>
       *
       * <code>uint64 contactless_floor_limit = 10;</code>
       * @param value The contactlessFloorLimit to set.
       * @return This builder for chaining.
       */
      public Builder setContactlessFloorLimit(long value) {
        copyOnWrite();
        instance.setContactlessFloorLimit(value);
        return this;
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Floor Limit
       * </pre>
       *
       * <code>uint64 contactless_floor_limit = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearContactlessFloorLimit() {
        copyOnWrite();
        instance.clearContactlessFloorLimit();
        return this;
      }

      /**
       * <pre>
       *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
       * </pre>
       *
       * <code>bytes reader_floor_limit = 11;</code>
       * @return The readerFloorLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getReaderFloorLimit() {
        return instance.getReaderFloorLimit();
      }
      /**
       * <pre>
       *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
       * </pre>
       *
       * <code>bytes reader_floor_limit = 11;</code>
       * @param value The readerFloorLimit to set.
       * @return This builder for chaining.
       */
      public Builder setReaderFloorLimit(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReaderFloorLimit(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Floor Limit, de 00000000h a FFFFFFFFh (4294967295), sendo o mesmo valor do objeto DF8123h, porém em formato binário (32 bits).
       * </pre>
       *
       * <code>bytes reader_floor_limit = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearReaderFloorLimit() {
        copyOnWrite();
        instance.clearReaderFloorLimit();
        return this;
      }

      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_no_on_device = 12;</code>
       * @return The limitNoOnDevice.
       */
      @java.lang.Override
      public long getLimitNoOnDevice() {
        return instance.getLimitNoOnDevice();
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_no_on_device = 12;</code>
       * @param value The limitNoOnDevice to set.
       * @return This builder for chaining.
       */
      public Builder setLimitNoOnDevice(long value) {
        copyOnWrite();
        instance.setLimitNoOnDevice(value);
        return this;
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (No On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_no_on_device = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimitNoOnDevice() {
        copyOnWrite();
        instance.clearLimitNoOnDevice();
        return this;
      }

      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_on_device = 13;</code>
       * @return The limitOnDevice.
       */
      @java.lang.Override
      public long getLimitOnDevice() {
        return instance.getLimitOnDevice();
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_on_device = 13;</code>
       * @param value The limitOnDevice to set.
       * @return This builder for chaining.
       */
      public Builder setLimitOnDevice(long value) {
        copyOnWrite();
        instance.setLimitOnDevice(value);
        return this;
      }
      /**
       * <pre>
       *Reader/Terminal Contactless Transaction Limit (On-device CVM)
       * </pre>
       *
       * <code>uint64 limit_on_device = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimitOnDevice() {
        copyOnWrite();
        instance.clearLimitOnDevice();
        return this;
      }

      /**
       * <pre>
       *Reader/Terminal CVM Required Limit
       * </pre>
       *
       * <code>uint64 cvm_required_limit = 14;</code>
       * @return The cvmRequiredLimit.
       */
      @java.lang.Override
      public long getCvmRequiredLimit() {
        return instance.getCvmRequiredLimit();
      }
      /**
       * <pre>
       *Reader/Terminal CVM Required Limit
       * </pre>
       *
       * <code>uint64 cvm_required_limit = 14;</code>
       * @param value The cvmRequiredLimit to set.
       * @return This builder for chaining.
       */
      public Builder setCvmRequiredLimit(long value) {
        copyOnWrite();
        instance.setCvmRequiredLimit(value);
        return this;
      }
      /**
       * <pre>
       *Reader/Terminal CVM Required Limit
       * </pre>
       *
       * <code>uint64 cvm_required_limit = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearCvmRequiredLimit() {
        copyOnWrite();
        instance.clearCvmRequiredLimit();
        return this;
      }

      /**
       * <pre>
       *Terminal Capabilities 
       * </pre>
       *
       * <code>bytes terminal_capabilities = 15;</code>
       * @return The terminalCapabilities.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerminalCapabilities() {
        return instance.getTerminalCapabilities();
      }
      /**
       * <pre>
       *Terminal Capabilities 
       * </pre>
       *
       * <code>bytes terminal_capabilities = 15;</code>
       * @param value The terminalCapabilities to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalCapabilities(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTerminalCapabilities(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Capabilities 
       * </pre>
       *
       * <code>bytes terminal_capabilities = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalCapabilities() {
        copyOnWrite();
        instance.clearTerminalCapabilities();
        return this;
      }

      /**
       * <pre>
       *Additional Terminal Capabilities
       * </pre>
       *
       * <code>bytes addictional_terminal_capabilities = 16;</code>
       * @return The addictionalTerminalCapabilities.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAddictionalTerminalCapabilities() {
        return instance.getAddictionalTerminalCapabilities();
      }
      /**
       * <pre>
       *Additional Terminal Capabilities
       * </pre>
       *
       * <code>bytes addictional_terminal_capabilities = 16;</code>
       * @param value The addictionalTerminalCapabilities to set.
       * @return This builder for chaining.
       */
      public Builder setAddictionalTerminalCapabilities(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAddictionalTerminalCapabilities(value);
        return this;
      }
      /**
       * <pre>
       *Additional Terminal Capabilities
       * </pre>
       *
       * <code>bytes addictional_terminal_capabilities = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddictionalTerminalCapabilities() {
        copyOnWrite();
        instance.clearAddictionalTerminalCapabilities();
        return this;
      }

      /**
       * <pre>
       *Application Version Number - EMV
       * </pre>
       *
       * <code>bytes application_version_number = 17;</code>
       * @return The applicationVersionNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getApplicationVersionNumber() {
        return instance.getApplicationVersionNumber();
      }
      /**
       * <pre>
       *Application Version Number - EMV
       * </pre>
       *
       * <code>bytes application_version_number = 17;</code>
       * @param value The applicationVersionNumber to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationVersionNumber(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setApplicationVersionNumber(value);
        return this;
      }
      /**
       * <pre>
       *Application Version Number - EMV
       * </pre>
       *
       * <code>bytes application_version_number = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationVersionNumber() {
        copyOnWrite();
        instance.clearApplicationVersionNumber();
        return this;
      }

      /**
       * <pre>
       *Card Data Input Capability
       * </pre>
       *
       * <code>bytes card_data_input_capability = 18;</code>
       * @return The cardDataInputCapability.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCardDataInputCapability() {
        return instance.getCardDataInputCapability();
      }
      /**
       * <pre>
       *Card Data Input Capability
       * </pre>
       *
       * <code>bytes card_data_input_capability = 18;</code>
       * @param value The cardDataInputCapability to set.
       * @return This builder for chaining.
       */
      public Builder setCardDataInputCapability(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCardDataInputCapability(value);
        return this;
      }
      /**
       * <pre>
       *Card Data Input Capability
       * </pre>
       *
       * <code>bytes card_data_input_capability = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardDataInputCapability() {
        copyOnWrite();
        instance.clearCardDataInputCapability();
        return this;
      }

      /**
       * <pre>
       *CVM Capability - CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_required = 19;</code>
       * @return The cvmCapabilityRequired.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCvmCapabilityRequired() {
        return instance.getCvmCapabilityRequired();
      }
      /**
       * <pre>
       *CVM Capability - CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_required = 19;</code>
       * @param value The cvmCapabilityRequired to set.
       * @return This builder for chaining.
       */
      public Builder setCvmCapabilityRequired(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCvmCapabilityRequired(value);
        return this;
      }
      /**
       * <pre>
       *CVM Capability - CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_required = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearCvmCapabilityRequired() {
        copyOnWrite();
        instance.clearCvmCapabilityRequired();
        return this;
      }

      /**
       * <pre>
       *CVM Capability - No CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_not_required = 20;</code>
       * @return The cvmCapabilityNotRequired.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCvmCapabilityNotRequired() {
        return instance.getCvmCapabilityNotRequired();
      }
      /**
       * <pre>
       *CVM Capability - No CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_not_required = 20;</code>
       * @param value The cvmCapabilityNotRequired to set.
       * @return This builder for chaining.
       */
      public Builder setCvmCapabilityNotRequired(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCvmCapabilityNotRequired(value);
        return this;
      }
      /**
       * <pre>
       *CVM Capability - No CVM Required
       * </pre>
       *
       * <code>bytes cvm_capability_not_required = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearCvmCapabilityNotRequired() {
        copyOnWrite();
        instance.clearCvmCapabilityNotRequired();
        return this;
      }

      /**
       * <pre>
       *Security Capability 
       * </pre>
       *
       * <code>bytes security_capability = 21;</code>
       * @return The securityCapability.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSecurityCapability() {
        return instance.getSecurityCapability();
      }
      /**
       * <pre>
       *Security Capability 
       * </pre>
       *
       * <code>bytes security_capability = 21;</code>
       * @param value The securityCapability to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCapability(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecurityCapability(value);
        return this;
      }
      /**
       * <pre>
       *Security Capability 
       * </pre>
       *
       * <code>bytes security_capability = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityCapability() {
        copyOnWrite();
        instance.clearSecurityCapability();
        return this;
      }

      /**
       * <pre>
       *Terminal Action Code - Default
       * </pre>
       *
       * <code>bytes terminal_action_code_default = 22;</code>
       * @return The terminalActionCodeDefault.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerminalActionCodeDefault() {
        return instance.getTerminalActionCodeDefault();
      }
      /**
       * <pre>
       *Terminal Action Code - Default
       * </pre>
       *
       * <code>bytes terminal_action_code_default = 22;</code>
       * @param value The terminalActionCodeDefault to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalActionCodeDefault(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTerminalActionCodeDefault(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Action Code - Default
       * </pre>
       *
       * <code>bytes terminal_action_code_default = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalActionCodeDefault() {
        copyOnWrite();
        instance.clearTerminalActionCodeDefault();
        return this;
      }

      /**
       * <pre>
       *Terminal Action Code - Denial
       * </pre>
       *
       * <code>bytes terminal_action_code_denial = 23;</code>
       * @return The terminalActionCodeDenial.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerminalActionCodeDenial() {
        return instance.getTerminalActionCodeDenial();
      }
      /**
       * <pre>
       *Terminal Action Code - Denial
       * </pre>
       *
       * <code>bytes terminal_action_code_denial = 23;</code>
       * @param value The terminalActionCodeDenial to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalActionCodeDenial(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTerminalActionCodeDenial(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Action Code - Denial
       * </pre>
       *
       * <code>bytes terminal_action_code_denial = 23;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalActionCodeDenial() {
        copyOnWrite();
        instance.clearTerminalActionCodeDenial();
        return this;
      }

      /**
       * <pre>
       *Terminal Action Code - Online
       * </pre>
       *
       * <code>bytes terminal_action_code_online = 24;</code>
       * @return The terminalActionCodeOnline.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerminalActionCodeOnline() {
        return instance.getTerminalActionCodeOnline();
      }
      /**
       * <pre>
       *Terminal Action Code - Online
       * </pre>
       *
       * <code>bytes terminal_action_code_online = 24;</code>
       * @param value The terminalActionCodeOnline to set.
       * @return This builder for chaining.
       */
      public Builder setTerminalActionCodeOnline(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTerminalActionCodeOnline(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Action Code - Online
       * </pre>
       *
       * <code>bytes terminal_action_code_online = 24;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerminalActionCodeOnline() {
        copyOnWrite();
        instance.clearTerminalActionCodeOnline();
        return this;
      }

      /**
       * <pre>
       *Terminal Risk Management Data
       * </pre>
       *
       * <code>bytes risk_management_data = 25;</code>
       * @return The riskManagementData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRiskManagementData() {
        return instance.getRiskManagementData();
      }
      /**
       * <pre>
       *Terminal Risk Management Data
       * </pre>
       *
       * <code>bytes risk_management_data = 25;</code>
       * @param value The riskManagementData to set.
       * @return This builder for chaining.
       */
      public Builder setRiskManagementData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRiskManagementData(value);
        return this;
      }
      /**
       * <pre>
       *Terminal Risk Management Data
       * </pre>
       *
       * <code>bytes risk_management_data = 25;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskManagementData() {
        copyOnWrite();
        instance.clearRiskManagementData();
        return this;
      }

      /**
       * <pre>
       *Transaction Category Code 
       * </pre>
       *
       * <code>bytes category_code = 26;</code>
       * @return The categoryCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCategoryCode() {
        return instance.getCategoryCode();
      }
      /**
       * <pre>
       *Transaction Category Code 
       * </pre>
       *
       * <code>bytes category_code = 26;</code>
       * @param value The categoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryCode(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCategoryCode(value);
        return this;
      }
      /**
       * <pre>
       *Transaction Category Code 
       * </pre>
       *
       * <code>bytes category_code = 26;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategoryCode() {
        copyOnWrite();
        instance.clearCategoryCode();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.ApplicationIdentifier)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "applicationIdentifier_",
              "generalFlags_",
              "authorizedAmount_",
              "countryCode_",
              "currencyCode_",
              "currencyExponent_",
              "terminalType_",
              "merchantCategoryCode_",
              "terminalTransactionQualifiers_",
              "contactlessFloorLimit_",
              "readerFloorLimit_",
              "limitNoOnDevice_",
              "limitOnDevice_",
              "cvmRequiredLimit_",
              "terminalCapabilities_",
              "addictionalTerminalCapabilities_",
              "applicationVersionNumber_",
              "cardDataInputCapability_",
              "cvmCapabilityRequired_",
              "cvmCapabilityNotRequired_",
              "securityCapability_",
              "terminalActionCodeDefault_",
              "terminalActionCodeDenial_",
              "terminalActionCodeOnline_",
              "riskManagementData_",
              "categoryCode_",
            };
            java.lang.String info =
                "\u0000\u001a\u0000\u0000\u0001\u001a\u001a\u0000\u0000\u0000\u0001\n\u0002\t\u0003" +
                "\u0003\u0004\u000b\u0005\u000b\u0006\u000b\u0007\u000b\b\u000b\t\n\n\u0003\u000b" +
                "\n\f\u0003\r\u0003\u000e\u0003\u000f\n\u0010\n\u0011\n\u0012\n\u0013\n\u0014\n\u0015" +
                "\n\u0016\n\u0017\n\u0018\n\u0019\n\u001a\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.ApplicationIdentifier)
    private static final com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier DEFAULT_INSTANCE;
    static {
      ApplicationIdentifier defaultInstance = new ApplicationIdentifier();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ApplicationIdentifier.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.ApplicationIdentifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ApplicationIdentifier> PARSER;

    public static com.google.protobuf.Parser<ApplicationIdentifier> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GeneralFlagsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axis.transactions.GeneralFlags)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @return The enum numeric value on the wire for flagType.
     */
    int getFlagTypeValue();
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @return The flagType.
     */
    com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType getFlagType();

    /**
     * <pre>
     *Deve ser conferida a data de validade do cartão
     * </pre>
     *
     * <code>bool validate_card_date = 2;</code>
     * @return The validateCardDate.
     */
    boolean getValidateCardDate();
  }
  /**
   * Protobuf type {@code axis.transactions.GeneralFlags}
   */
  public  static final class GeneralFlags extends
      com.google.protobuf.GeneratedMessageLite<
          GeneralFlags, GeneralFlags.Builder> implements
      // @@protoc_insertion_point(message_implements:axis.transactions.GeneralFlags)
      GeneralFlagsOrBuilder {
    private GeneralFlags() {
    }
    public static final int FLAG_TYPE_FIELD_NUMBER = 1;
    private int flagType_;
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @return The enum numeric value on the wire for flagType.
     */
    @java.lang.Override
    public int getFlagTypeValue() {
      return flagType_;
    }
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @return The flagType.
     */
    @java.lang.Override
    public com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType getFlagType() {
      com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType result = com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType.forNumber(flagType_);
      return result == null ? com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @param value The enum numeric value on the wire for flagType to set.
     */
    private void setFlagTypeValue(int value) {
        flagType_ = value;
    }
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     * @param value The flagType to set.
     */
    private void setFlagType(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType value) {
      flagType_ = value.getNumber();
      
    }
    /**
     * <pre>
     *Flags gerais (objeto DFFF01h)
     * </pre>
     *
     * <code>.axis.transactions.FlagType flag_type = 1;</code>
     */
    private void clearFlagType() {
      
      flagType_ = 0;
    }

    public static final int VALIDATE_CARD_DATE_FIELD_NUMBER = 2;
    private boolean validateCardDate_;
    /**
     * <pre>
     *Deve ser conferida a data de validade do cartão
     * </pre>
     *
     * <code>bool validate_card_date = 2;</code>
     * @return The validateCardDate.
     */
    @java.lang.Override
    public boolean getValidateCardDate() {
      return validateCardDate_;
    }
    /**
     * <pre>
     *Deve ser conferida a data de validade do cartão
     * </pre>
     *
     * <code>bool validate_card_date = 2;</code>
     * @param value The validateCardDate to set.
     */
    private void setValidateCardDate(boolean value) {
      
      validateCardDate_ = value;
    }
    /**
     * <pre>
     *Deve ser conferida a data de validade do cartão
     * </pre>
     *
     * <code>bool validate_card_date = 2;</code>
     */
    private void clearValidateCardDate() {
      
      validateCardDate_ = false;
    }

    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code axis.transactions.GeneralFlags}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags, Builder> implements
        // @@protoc_insertion_point(builder_implements:axis.transactions.GeneralFlags)
        com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlagsOrBuilder {
      // Construct using com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *Flags gerais (objeto DFFF01h)
       * </pre>
       *
       * <code>.axis.transactions.FlagType flag_type = 1;</code>
       * @return The enum numeric value on the wire for flagType.
       */
      @java.lang.Override
      public int getFlagTypeValue() {
        return instance.getFlagTypeValue();
      }
      /**
       * <pre>
       *Flags gerais (objeto DFFF01h)
       * </pre>
       *
       * <code>.axis.transactions.FlagType flag_type = 1;</code>
       * @param value The flagType to set.
       * @return This builder for chaining.
       */
      public Builder setFlagTypeValue(int value) {
        copyOnWrite();
        instance.setFlagTypeValue(value);
        return this;
      }
      /**
       * <pre>
       *Flags gerais (objeto DFFF01h)
       * </pre>
       *
       * <code>.axis.transactions.FlagType flag_type = 1;</code>
       * @return The flagType.
       */
      @java.lang.Override
      public com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType getFlagType() {
        return instance.getFlagType();
      }
      /**
       * <pre>
       *Flags gerais (objeto DFFF01h)
       * </pre>
       *
       * <code>.axis.transactions.FlagType flag_type = 1;</code>
       * @param value The enum numeric value on the wire for flagType to set.
       * @return This builder for chaining.
       */
      public Builder setFlagType(com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.FlagType value) {
        copyOnWrite();
        instance.setFlagType(value);
        return this;
      }
      /**
       * <pre>
       *Flags gerais (objeto DFFF01h)
       * </pre>
       *
       * <code>.axis.transactions.FlagType flag_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlagType() {
        copyOnWrite();
        instance.clearFlagType();
        return this;
      }

      /**
       * <pre>
       *Deve ser conferida a data de validade do cartão
       * </pre>
       *
       * <code>bool validate_card_date = 2;</code>
       * @return The validateCardDate.
       */
      @java.lang.Override
      public boolean getValidateCardDate() {
        return instance.getValidateCardDate();
      }
      /**
       * <pre>
       *Deve ser conferida a data de validade do cartão
       * </pre>
       *
       * <code>bool validate_card_date = 2;</code>
       * @param value The validateCardDate to set.
       * @return This builder for chaining.
       */
      public Builder setValidateCardDate(boolean value) {
        copyOnWrite();
        instance.setValidateCardDate(value);
        return this;
      }
      /**
       * <pre>
       *Deve ser conferida a data de validade do cartão
       * </pre>
       *
       * <code>bool validate_card_date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidateCardDate() {
        copyOnWrite();
        instance.clearValidateCardDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:axis.transactions.GeneralFlags)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "flagType_",
              "validateCardDate_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0007" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags> parser = PARSER;
          if (parser == null) {
            synchronized (com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:axis.transactions.GeneralFlags)
    private static final com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags DEFAULT_INSTANCE;
    static {
      GeneralFlags defaultInstance = new GeneralFlags();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GeneralFlags.class, defaultInstance);
    }

    public static com.axismobfintech.gpb.transactions.ApplicationIdentifierOuterClass.GeneralFlags getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GeneralFlags> PARSER;

    public static com.google.protobuf.Parser<GeneralFlags> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
